### ISSUE TITLE
Cannot remove the mail permission to a user (3.7 testing)

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#1427] opened 2019-09-03 11:03 UTC
I am testing the new permission system.

And i am trying to remove a user from mail permission, but i fail to do it:
```
root@yunohost:/ynh-dev# yunohost user permission remove mail -u toto -p main --debug
89   DEBUG loading actions map namespace 'yunohost'
99   DEBUG extra parameter classes loaded: ['comment', 'ask', 'password', 'required', 'pattern']
152  DEBUG initializing base actions map parser for cli
153  DEBUG registering new callback action 'yunohost.utils.packages.ynh_packages_version' to ['-v', '--version']
206  DEBUG acquiring lock...
223  DEBUG lock has been acquired
228  DEBUG loading python module yunohost.user took 0.005s
228  INFO processing action [14323.1]: yunohost.user.permission.remove with args={'username': ['toto'], 'app': ['mail'], 'group': None, 'permission': ['main']}
243  DEBUG initialize authenticator 'as-root' with: uri='ldapi://%2Fvar%2Frun%2Fslapd%2Fldapi', base_dn='dc=yunohost,dc=org', user_rdn='gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth'
246  WARNING Group 'toto' already has permissions 'main' disabled for app 'mail'
259  DEBUG The permission database has been updated
493  DEBUG The SSOwat configuration has been generated
501  DEBUG system hook folder not found for action 'post_app_removeaccess' in /usr/share/yunohost/hooks/
502  DEBUG custom hook folder not found for action 'post_app_removeaccess' in /etc/yunohost/hooks.d/
504  DEBUG To view the log of the operation 'Update 'mail' permission', use the command 'yunohost log display 20190903-105242-user_permission_remove-mail'
506  DEBUG action [14323.1] executed in 0.278s
507  DEBUG lock has been released
permissions: 
  mail: 
    main: 
      allowed_groups: 
      allowed_users: toto
```
So toto is still here and authorized to receive email (i checked it).
Note toto group has been removed correctly (here is the log of the second time i ran the command, that's why it says toto group is already removed).

**Comment by zamentur** [comment] 2019-09-03 11:04
```
user_rdn='gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth'
```
Seems strange...

**Comment by Josue-T** [comment] 2019-09-03 11:48
Hello,

> ```
> user_rdn='gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth'
> ```
> 
> Seems strange...

This is true. It's for the root authentication.

> Note toto group has been removed correctly (here is the log of the second time i ran the command, that's why it says toto group is already removed).

It's strange because the permission for the user and for the group is same.

What is the result of `slapcat -a "cn=mail"` ?

**Comment by zamentur** [comment] 2019-09-03 11:53
```
root@yunohost:/ynh-dev# slapcat -a "cn=main.mail"
dn: cn=main.mail,ou=permission,dc=yunohost,dc=org
objectClass: posixGroup
objectClass: permissionYnh
gidNumber: 5001
cn: main.mail
structuralObjectClass: posixGroup
entryUUID: 4750f97c-627e-1039-9a6b-b93f94c3208f
creatorsName: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
createTimestamp: 20190903100644Z
memberUid: toto
inheritPermission: uid=toto,ou=users,dc=yunohost,dc=org
entryCSN: 20190903103233.724173Z#000000#000#000000
modifiersName: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
modifyTimestamp: 20190903103233Z
```

**Comment by zamentur** [comment] 2019-09-03 11:54
So `memberUid` is here but not `groupPermission`

**Comment by Josue-T** [comment] 2019-09-03 12:14
> ```
> memberUid: toto
> inheritPermission: uid=toto,ou=users,dc=yunohost,dc=org
> ```

It look like a bug because normally you shouldn't have only this for the permission. Probably doe to the function `permission_sync_to_user`. Can you give me exactly the process to reproduce this bug ?

**Comment by zamentur** [comment] 2019-09-03 12:16
Just 
```
yunohost user permission clear mail
yunohost user permission add mail -u test toto
yunohost user permission remove mail -u test
yunohost user permission remove mail -u toto
```

**Comment by Josue-T** [comment] 2019-09-03 12:19
Ok thanks, I'll see

**Comment by alexAubin** [comment] 2019-09-22 18:00
Should be fixed now

**Closed as completed by alexAubin** 2019-09-22 18:00 UTC
Labels: :busts_in_silhouette: User management
