### ISSUE TITLE
Yunohost on Raspberry Pi 400 (kit) 

### ISSUE THREAD

**Issue by TorstenEdler** [YunoHost/issues#1979] opened 2022-02-02 18:12 UTC
Just tried to install the latest version v4.1.7.2 on a Raspberry Pi 400 Kit.
The lan connection is not activated i.e. the pi does not get an ip address and it remains unreachable from another machine.
Logging into the system is possible - so a montor is a must to install.
I was able to activate wireless lan via raspi-config. But there were further issues with updating the system and required manual configuration which were beyond my capabilities and so i gave up.

**Comment by tituspijean** [comment] 2022-02-02 23:02
FYI latest version is actually 4.4.0. The RPi images are slightly outdated.

Since I think no contributors have a RPi 400 on hand, could you try to:

1. install instead a Raspberry Pi OS Lite image
2. Put an empty file named `ssh` in the /boot directory before plugging the SD card in the RPi 400 (to enable SSH connection)
3. Run YunoHost installation with the "remote server" method from the documentation. 

Report your findings then. ;)

**Comment by TorstenEdler** [comment] 2022-02-03 07:23
Thank you for taking the trouble.
Been there, done that and failed as well. I am unable to logon to the pi via ssh. I have searched the net several hours and tested many of the various offered solutions to the "ssh connection refused" problem. The ssh server on the pi is running, i know the right IP address. My Win-PC (with putty) is apparently not the problem because I can SSH into my NAS in the same network . AngryIP shows nevertheless that port 22 is not open on the PPI. I will give up and send the PI back. If i was looking for linux hell i would have bought a more "regular" device than a pi. So please, no more trouble, issue can be closed.

**Comment by tituspijean** [comment] 2022-02-03 12:38
If you cannot connect to your system after enabling the SSH service on a clean Raspberry Pi OS system, before installing YunoHost, then the issue is not with YunoHost. Closing.

**Closed as completed** 2022-02-03 12:38 UTC
