### ISSUE TITLE
Let's Encrypt button is disabled for subdomains

### ISSUE THREAD

**Issue by scottdky** [YunoHost/issues#2290] opened 2023-11-26 22:21 UTC
### Describe the bug

Some apps such as Invidious require a subdomain. After creating the subdomain, the Let's Encrypt button is disabled, so the subdomain cannot be accessed without a certificate. Editing the /etc/hosts file is a workaround.

This is a post for a workaround (https://forum.yunohost.org/t/cant-install-ssl-certificate-on-a-noho-st-subdomain/18727), but I found a simpler one, described below.

### Context
- Hardware: MiniPC 64-bit x86 CPU
- YunoHost version:
```$ sudo yunohost --version
yunohost: 
  repo: stable
  version: 11.2.6
yunohost-admin: 
  repo: stable
  version: 11.2.3
moulinette: 
  repo: stable
  version: 11.2
ssowat: 
  repo: stable
  version: 11.2
```
- OS: 
```Linux XXX.nohost.me 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux```

### To reproduce

1. Add a subdomain. 
2. Try to click on Let's Encrypt button. It is disabled.

### Workaround

Edit `/etc/hosts` and add this line:

`127.0.0.1 subdomain.maindomain` replacing the sub and main domain names with your own.

Save the file, and refresh the page for the subdomain. The Let's Encrypt button is now enabled and works.

When editing the file, I noticed this line had been added (before I added the one above):

`127.0.0.1 subdomain` 

It appears that change was insufficient.

**Comment by Tagadda** [comment] 2023-11-27 00:04
You have to run the diagnosis before you can install Let's Encrypt.

**Comment by scottdky** [comment] 2023-11-27 01:25
Is that for every time you want to do it? One thing I failed to mention is the subdomain is a subdomain of nohost.me, e.g. videos.mysite.nohost.me.

**Comment by Tagadda** [comment] 2023-11-27 07:41
Oh I don't think subdomain of a subdomain of a nohost.me doesn't work.
Can you share the result of your diagnosis please ?

**Comment by alexAubin** [comment] 2023-11-27 11:08
Pretty sure this is a duplicate of https://github.com/YunoHost/issues/issues/1846 / https://github.com/YunoHost/issues/issues/2006 / https://github.com/YunoHost/issues/issues/1634

**Comment by alexAubin** [comment] 2024-01-27 15:53
Closing as duplicate of https://github.com/YunoHost/issues/issues/1634

**Closed as completed by alexAubin** 2024-01-27 15:53 UTC
Labels: :lock: Certificate, Domain management
