### ISSUE TITLE
Adding a new domain should automatically run the domain diagnosis in the background

### ISSUE THREAD

**Issue by Limezy** [YunoHost/issues#2006] opened 2022-04-22 05:01 UTC
I always find the current workflow to add a domain secured by SSL a little bit tricky : 
1. Go to domain section, add a domain. At this moment I can't add a let's encrypt certificate
2. Once done, go back to the webadmin root and go to diagnosis
3. Run the full diagnosis (long time to wait...)
4. Once done, go back to the webadmin root and go to domain section to add my let's encrypt certificate

Wouldn't it be easier if everytime a domain is added, the dedicated diagnosis section (domains) would be run ?

**Comment by alexAubin** [comment] 2022-11-20 19:42
Duplicate of https://github.com/YunoHost/issues/issues/1634

**Closed as completed by alexAubin** 2022-11-20 19:42 UTC
