### ISSUE TITLE
Port 8095 is open but diagnostic shows it closed

### ISSUE THREAD

**Issue by biva** [YunoHost/issues#2173] opened 2023-03-10 11:02 UTC
### Describe the bug

I configured the port 8095 on my ISP's router to be forwarded to my Yunohost server, for the app Wireguard. Wireguard works fine now. But the diagnostic shows it's not open:

![image](https://user-images.githubusercontent.com/9964305/224298924-ee1992c5-1777-4078-872e-0d258639b901.png)

@tituspijean reported the same issue and thinks it's a bug of Yunohost (https://forum.yunohost.org/t/wireguard-virtual-private-network/12928/65). This is not preventing Wireguard to work, but this is confusing for the admin user: is there a possibility to solve it or to clarify the message?

**Comment by tituspijean** [comment] 2023-03-10 12:55
Duplicate of https://github.com/YunoHost/issues/issues/1914. 😇

**Closed as not planned by tituspijean** 2023-03-10 12:55 UTC

**Comment by biva** [comment] 2023-03-10 13:30
Oh, sorry for that, I searched for 8095 and didn't find any topic. Thanks!
