### ISSUE TITLE
markupsafe last version is breaking pyhton 3 and nginx. Lets encrypt renewal was broken due to this

### ISSUE THREAD

**Issue by niouniou49** [YunoHost/issues#2092] opened 2022-11-23 03:46 UTC
### Describe the bug

the last update of yunohost broke python3 and it was not possible to run any command to regenerate the nginx config.
that broke the process to renew the lets encrypt certificate

### Context

- Hardware: 1&1 VPS
- YunoHost version: 11.1.0.2
- I have access to my server: Through SSH and through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no tweak
  
### To reproduce

- upgrade to 11.1.0.2 and try to refresh the lets encrypt certificate
-  try to run yunohost tools regen-conf nginx --force

### Expected behavior
the 2 command above will fail with python3 error message (see logs)

### Logs

[logs 22NOV2022.docx](https://github.com/YunoHost/issues/files/10072682/logs.22NOV2022.docx)

fix was possible by running this command
fix : pip install markupsafe==2.0.1

also had to fix postifx certificate postmap by running
cd /etc/postfix; postmap -F sni

**Comment by alexAubin** [comment] 2022-11-29 17:43
Well idk, is the issue really on YunoHost's side ? Naively it rather sound like you had markupsafe installed globally via `pip`, with a specific version that broke other things, maybe because of a specific app or idk ...

The expected version of markupsafe on Bullseye is expected to be 1.1.1 : https://packages.debian.org/bullseye/python3-markupsafe

**Comment by alexAubin** [comment] 2022-11-29 17:45
This is confirmed in your log, the issue was in: 

```
/usr/local/lib/python3.9/dist-packages/markupsafe/__init__.py
```

note the `/usr/local/lib` which points to the fact that it was a packaged installed globally with `pip` that's causing the issue, so either an app (in which case it would be nice to know which one) or some manual stuff on your side

Closing because the bug is not on YunoHost's side / can't reproduce without more info

**Closed as completed by alexAubin** 2022-11-29 17:45 UTC
