### ISSUE TITLE
Trouble installing in a non-SSE3 box

### ISSUE THREAD

**Issue by marcogaio** [YunoHost/issues#2263] opened 2023-10-06 12:44 UTC
First, my kudos for the project, wonderful!

I've tried to install YunoHost on a non-SSE3 box (and old HP MicoServer, AMD Turion(tm) II Neo N40L Dual-Core Processor; effectively, i'm installed it on a VM on PVE8, installed on that hardware, but SSE3 instruction set seems cannot be emulated by QEmu, so it is of little difference).

Installation half-failed (stopped installing software, but was able to continue installing boot loader and so now the VM boot), and after the install i see:
```
root@yunohost:~# apt dist-upgrade
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze... Fatto
Lettura informazioni sullo stato... Fatto   
Calcolo dell'aggiornamento... Fatto
I seguenti pacchetti saranno RIMOSSI:
  systemd-timesyncd
I seguenti pacchetti NUOVI saranno installati:
  acl apparmor at bc build-essential curl equivs fake-hwclock firmware-linux-free g++ g++-10 galera-4 gawk git git-man gsasl-common guile-2.2-libs haveged jq libaio1 libauthen-sasl-perl libcgi-fast-perl
  libcgi-pm-perl libclone-perl libconfig-inifiles-perl libconvert-asn1-perl libcurl4 libdata-dump-perl libdbd-ldap-perl libdbd-mariadb-perl libdbi-perl libencode-locale-perl libevent-2.1-7
  libevent-core-2.1-7 libevent-pthreads-2.1-7 libexpat1-dev libfcgi-bin libfcgi-perl libfcgi0ldbl libfile-listing-perl libfl2 libfont-afm-perl libfribidi0 libgc1 libgsasl7 libgssapi-perl libhavege2
  libhtml-form-perl libhtml-format-perl libhtml-parser-perl libhtml-tagset-perl libhtml-template-perl libhtml-tree-perl libhttp-cookies-perl libhttp-daemon-perl libhttp-date-perl libhttp-message-perl
  libhttp-negotiate-perl libhyperscan5 libidn11 libio-html-perl libio-socket-ssl-perl libjemalloc2 libjq1 libjs-sphinxdoc libjs-underscore liblua5.1-0 liblwp-mediatypes-perl liblwp-protocol-https-perl
  liblzf1 libmailtools-perl libmailutils7 libmariadb3 libmemcached11 libnet-http-perl libnet-ldap-perl libnet-smtp-ssl-perl libnet-ssleay-perl libntlm0 libonig5 libopendbx1 libopendbx1-sqlite3
  libopendkim11 libopts25 libpython3-dev libpython3.9 libpython3.9-dev librbl1 libsnappy1v5 libstdc++-10-dev libterm-readkey-perl libtimedate-perl libtry-tiny-perl libunbound8 libunwind8 libvbr2
  libwww-perl libwww-robotrules-perl linux-image-5.10.0-25-amd64 lua-bitop lua-cjson lua-event lua-expat lua-sec lua-zlib lua5.3 mailutils mailutils-common mariadb-client-10.5 mariadb-client-core-10.5
  mariadb-common mariadb-server mariadb-server-10.5 mariadb-server-core-10.5 metronome mysql-common ntp opendkim-tools perl-openssl-defaults php-common php-mbstring php-pear php-php-gettext php-xml
  php7.4-cli php7.4-common php7.4-curl php7.4-fpm php7.4-gd php7.4-intl php7.4-json php7.4-ldap php7.4-mbstring php7.4-mysql php7.4-opcache php7.4-readline php7.4-xml postsrsd procmail python-pip-whl
  python3-dev python3-distro-info python3-distutils python3-pip python3-setuptools python3-wheel python3.9-dev redis-server redis-tools rspamd rsync sntp socat unattended-upgrades unzip yunohost
  yunohost-admin zlib1g-dev
I seguenti pacchetti saranno aggiornati:
  debian-archive-keyring dpkg-dev file isc-dhcp-client isc-dhcp-common libc-l10n libdpkg-perl libgnutls30 libgssapi-krb5-2 libjson-c5 libk5crypto3 libkrb5-3 libkrb5support0 libmagic-mgc libmagic1
  libncurses6 libncursesw6 libnftables1 libpcre2-8-0 libssl1.1 libtasn1-6 libtinfo6 libudev1 libxml2 linux-image-amd64 locales nano nftables systemd-sysv tzdata udev
31 aggiornati, 158 installati, 1 da rimuovere e 0 non aggiornati.
È necessario scaricare 0 B/154 MB di archivi.
Dopo quest'operazione, verranno occupati 742 MB di spazio su disco.
Continuare? [S/n] 
Lettura dei changelog... Fatto
Estrazione dei template dai pacchetti: 100%
Preconfigurazione dei pacchetti in corso
(Lettura del database... 38448 file e directory attualmente installati.)
Preparativi per estrarre .../libhyperscan5_5.4.0-2_amd64.deb...
Aborting installation because of missing SSSE3 extension.
dpkg: errore nell'elaborare l'archivio /var/cache/apt/archives/libhyperscan5_5.4.0-2_amd64.deb (--unpack):
 il sottoprocesso nuovo pacchetto libhyperscan5 script pre-installation ha restituito lo stato di errore 1
Si sono verificati degli errori nell'elaborazione:
 /var/cache/apt/archives/libhyperscan5_5.4.0-2_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Googling around lead me to:
  https://forum.yunohost.org/t/alpha-stage-testing-for-yunohost-11-0-on-debian-bullseye-and-migration-that-will-be-shipped-in-yunohost-4-4-x/18014/30
  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1020225

so seems clearly a known problem at least in alpha test stage, and it is NOT a YunoHost bug, but a bug of libhyperscan5 library; as debian BTS say, this is a very bad policy behaviour for the package, that cannot fail the installation for an instruction set missing, and pretend to be multiarchitecture.

I think two path could be taken:
a) (if possible) relax dependencies on libhyperscan5, so yunohost packages can be installed without that library.
b) provide in yunohost reository the libhyperscan5 package recompiled without the preinstall check.

Thanks.

**Comment by alexAubin** [comment] 2023-10-06 12:48
(It seems to be a dependency of rspamd x_x)

**Comment by marcogaio** [comment] 2023-10-06 13:02
For reference: because libhyperscan5 debian package have only a `preinst` script that do only the SS3 check and not a `postinst` one, i've temporary edited `/usr/share/debconf/confmodule` adding an `exit 0` at the top, then do:

```
apt install libhyperscan5
```
and then removed the `exit 0` from debconf shell library returning to the original unmodified script.

Absolutely crude hack, but worked. ;-)

**Comment by chri2** [comment] 2023-10-19 18:05
The problem is reproducible on an Opteron_G1. The bookworm rspamd I tried to install pulled in libhyperscan5 which in turn asked for confirmation that I really wanted to install it.

![Screenshot_yunohost_2023-10-19_19:58:55](https://github.com/YunoHost/issues/assets/15866990/f8635389-1a37-402b-b975-d8debe1c7f38)

**Comment by alexAubin** [comment] 2024-01-27 22:54
Closing because we're removing rspamd from the default install in bookworm

**Closed as completed by alexAubin** 2024-01-27 22:54 UTC

**Comment by chri2** [comment] 2024-01-28 20:03
Will it be available in some way beside installing it manually via apt?

**Comment by alexAubin** [comment] 2024-01-28 20:07
Yes, in the global mail settings
