### ISSUE TITLE
New Install brings in repo sury.org without gpg key

### ISSUE THREAD

**Issue by Beeblebrox-BSD** [YunoHost/issues#2109] opened 2022-12-21 02:12 UTC
I just did a clean install of Bullseye. I see below entry in apt sources, but the GPG key was not imported (I imported the key manually). SHA of downloaded iso matches value on download page.
`deb https://packages.sury.org/php/ bullseye main`

Please advise if this is NOT a new php repo for YNH.

**Comment by alexAubin** [comment] 2022-12-21 17:41
Can you share the output of `yunohost tools regen-conf apt --debug`

Also can you confirm that network was up during the server postinstall ...

**Comment by Beeblebrox-BSD** [comment] 2022-12-21 19:29
> can you confirm that network was up during the server postinstall

Yes it was

**output of yunohost tools regen-conf apt --debug:**
```
121  DEBUG initializing base actions map parser for cli
122  DEBUG loading actions map
123  DEBUG building parser...
132  DEBUG building parser took 0.009s
133  DEBUG acquiring lock...
144  DEBUG lock has been acquired
162  DEBUG loading python module yunohost.tools took 0.018s
163  DEBUG processing action [4549.1]: yunohost.tools.regen-conf with args={'names': ['apt'], 'with_diff': False, 'force': False, 'dry_run': False, 'list_pending': False}
241  DEBUG initializing ldap interface
252  DEBUG Executing command '['sh', '-c', '/bin/bash -x "./10-apt" pre \'\' \'\' /var/cache/yunohost/regenconf/pending/apt 7>&1']'
258  DEBUG + set -e
259  DEBUG + do_pre_regen /var/cache/yunohost/regenconf/pending/apt
259  DEBUG + pending_dir=/var/cache/yunohost/regenconf/pending/apt
259  DEBUG + mkdir --parents /var/cache/yunohost/regenconf/pending/apt/etc/apt/preferences.d
260  DEBUG + mkdir -p /var/cache/yunohost/regenconf/pending/apt/etc/apt/sources.list.d/
261  DEBUG ++ lsb_release --codename --short
311  DEBUG + echo 'deb https://packages.sury.org/php/ bullseye main'
311  DEBUG + echo '
311  DEBUG Package: php-common
311  DEBUG Pin: origin "packages.sury.org"
312  DEBUG Pin-Priority: 500'
312  DEBUG + packages_to_refuse_from_sury='php php-* openssl libssl1.1 libssl-dev'
312  DEBUG + for package in $packages_to_refuse_from_sury
312  DEBUG + echo '
313  DEBUG Package: php
313  DEBUG Pin: origin "packages.sury.org"
313  DEBUG Pin-Priority: -1'
313  DEBUG + for package in $packages_to_refuse_from_sury
313  DEBUG + echo '
313  DEBUG Package: php-*
313  DEBUG Pin: origin "packages.sury.org"
314  DEBUG Pin-Priority: -1'
314  DEBUG + for package in $packages_to_refuse_from_sury
314  DEBUG + echo '
314  DEBUG Package: openssl
314  DEBUG Pin: origin "packages.sury.org"
314  DEBUG Pin-Priority: -1'
314  DEBUG + for package in $packages_to_refuse_from_sury
315  DEBUG + echo '
315  DEBUG Package: libssl1.1
315  DEBUG Pin: origin "packages.sury.org"
315  DEBUG Pin-Priority: -1'
315  DEBUG + for package in $packages_to_refuse_from_sury
315  DEBUG + echo '
315  DEBUG Package: libssl-dev
316  DEBUG Pin: origin "packages.sury.org"
316  DEBUG Pin-Priority: -1'
316  DEBUG + echo '
316  DEBUG 
316  DEBUG # PLEASE READ THIS WARNING AND DON'\''T EDIT THIS FILE
316  DEBUG 
316  DEBUG # You are probably reading this file because you tried to install apache2 or
317  DEBUG # bind9. These 2 packages conflict with YunoHost.
317  DEBUG 
317  DEBUG # Installing apache2 will break nginx and break the entire YunoHost ecosystem
317  DEBUG # on your server, therefore don'\''t remove those lines!
317  DEBUG 
317  DEBUG # You have been warned.
317  DEBUG 
318  DEBUG Package: apache2
318  DEBUG Pin: release *
318  DEBUG Pin-Priority: -1
318  DEBUG 
318  DEBUG Package: apache2-bin
318  DEBUG Pin: release *
318  DEBUG Pin-Priority: -1
319  DEBUG 
319  DEBUG # Also bind9 will conflict with dnsmasq.
319  DEBUG # Same story as for apache2.
319  DEBUG # Don'\''t install it, don'\''t remove those lines.
319  DEBUG 
319  DEBUG Package: bind9
319  DEBUG Pin: release *
320  DEBUG Pin-Priority: -1
320  DEBUG '
1321 DEBUG Checking pending configuration which would have been applied for category 'apt'...
1342 DEBUG processing pending conf '/var/cache/yunohost/regenconf/pending/apt/etc/apt/sources.list.d/extra_php_version.list' to system conf '/etc/apt/sources.list.d/extra_php_version.list'
1343 INFO The configuration file '/etc/apt/sources.list.d/extra_php_version.list' was removed manually, and will not be created
1343 DEBUG processing pending conf '/var/cache/yunohost/regenconf/pending/apt/etc/apt/preferences.d/extra_php_version' to system conf '/etc/apt/preferences.d/extra_php_version'
1344 DEBUG > system conf is already up-to-date
1344 DEBUG processing pending conf '/var/cache/yunohost/regenconf/pending/apt/etc/apt/preferences.d/ban_packages' to system conf '/etc/apt/preferences.d/ban_packages'
1344 DEBUG > system conf is already up-to-date
1345 DEBUG Executing command '['sh', '-c', '/bin/bash -x "./10-apt" post \'\' \'\' \'\' 7>&1']'
1351 DEBUG + set -e
1351 DEBUG + do_post_regen
1351 DEBUG + regen_conf_files=
1352 DEBUG + [[ ! -s /etc/apt/trusted.gpg.d/extra_php_version.gpg ]]
1352 DEBUG + wget --timeout 900 --quiet https://packages.sury.org/php/apt.gpg --output-document=-
1352 DEBUG + gpg --dearmor
2194 DEBUG + update-alternatives --set php /usr/bin/php7.4
3198 DEBUG To view the log of the operation 'Regenerate system configurations 'apt'', use the command 'yunohost log show 20221221-192117-regen_conf-apt'
3206 DEBUG action [4549.1] executed in 3.043s
3206 DEBUG lock has been released
apt: 
  applied: 
  pending: 
    /etc/apt/sources.list.d/extra_php_version.list: 
      status: removed
```

**Comment by alexAubin** [comment] 2022-12-21 19:35
Well according to YunoHost:

>1343 INFO The configuration file '/etc/apt/sources.list.d/extra_php_version.list' was removed manually, and will not be created

Somehow you deleted this file maybe ...

And also I can see that it did download the key because `/etc/apt/trusted.gpg.d/extra_php_version.gpg` did not exist (or was empty)

Can you confirm that `test -s /etc/apt/trusted.gpg.d/extra_php_version.gpg && echo exist_and_non_empty && echo doesnt_exist_or_is_empty` does display "exist_and_non_empty" ?

**Comment by Beeblebrox-BSD** [comment] 2022-12-22 20:50
As I had stated in 1st post, I fixed the issue manually.
`apt update` was throwing out gpg key error messages, so;
I curl'ed the GPG key, then I imported the key through the CLI. The APT file name changed on its own after key import (if I remember correctly).

Any diagnostic output is of course going to display "manual"...

**Comment by alexAubin** [comment] 2022-12-22 21:39
We can't help if you don't answer questions that try to pinpoint the issue ... Also file don't magically change names nor disappear so idk, clearly it looks like we're missing pieces of the story

 Closing because there's no clue on how to reproduce the issue ...

**Closed as completed by alexAubin** 2022-12-22 21:39 UTC
