### ISSUE TITLE
Credit card for donation not accepted

### ISSUE THREAD

**Issue by Plumeros** [YunoHost/issues#2305] opened 2024-01-06 14:39 UTC
### Describe the bug
When trying to donate, unfortunately my credit card data is not accepted and the donation process is interrupted.
I tried the process twice. Other donations with the same credit card info worked fine.
I think the issue is on the side of stripe.com.
Maybe an alternative payment method would be recommended.
It is somehow the nature of this issue that I don't provide more info :)
But let me know once I should re-try the donation.

### To reproduce
1. Start the donation process at https://donate.yunohost.org/
2. choose an amount
3. Click "Donate"
-> forwarded to https://checkout.stripe.com/c/pay/cs_live_…
4. Enter all mandatory data and the "i am a human" approval
5. Click "Pay"
6. Credit card data is not accepted, see screenshot.
![Bildschirmfoto vom 2024-01-06 14-51-32](https://github.com/YunoHost/issues/assets/22871251/0d6f686c-07a2-4fce-9817-0c540c7fad20)

### Expected behavior
Credit card data is accepted and donation is successful.

**Comment by alexAubin** [comment] 2024-01-06 14:42
Cheers for donating (or at least attempting to :sweat_smile: )

Alternatively you could try donating via https://liberapay.com/YunoHost/ though it's not clear to me how it works nowadays, there was some changes a few years ago etc, it's a bit tricky to explain, maybe it doesnt matter

**Comment by Plumeros** [comment] 2024-01-06 16:45
Hi Aleks,

that was a surprisingly fast answer ;-)

https://liberapay.com/YunoHost/ 
works fine with my credit card. 

I would strongly recommend to update your donation page
https://donate.yunohost.org/ 
in order to offer multiple ways of payments.

**Comment by alexAubin** [comment] 2024-01-27 23:15
Closing as duplicate of https://github.com/YunoHost/issues/issues/2221 then

**Closed as not planned by alexAubin** 2024-01-27 23:15 UTC
