### ISSUE TITLE
Wrong flags in CAA DNS resource record

### ISSUE THREAD

**Issue by renne** [YunoHost/issues#2134] opened 2023-01-23 23:49 UTC
### Describe the bug

The CAA DNS resource records suggested by Yunohost/created by the autodns feature contain the wrong flag `128`.
According to [IETF RFC 6844](https://datatracker.ietf.org/doc/html/rfc6844#section-7.3) the only allowed flag is `0` which is enforced by nameserver providers (e.g. Cloudflare).
Yunohost diagnosis fails if nameserver providers adjust `128` to `0`.

### Context

- Hardware: Proxmox KVM on bare metal
- YunoHost version: 11.0.11
- I have access to my server: Through SSH | direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### To reproduce

Go to the DNS settings of a domain and view the suggested DNS CAA resource records -> `128 issue "letsencrypt.org"` statement.

### Expected behavior

Go to the DNS settings of a domain and view the suggested DNS CAA resource records -> `0 issue "letsencrypt.org"` statement.

This bug is related to bug #2128

**Comment by renne** [comment] 2023-01-27 20:28
@alexAubin 
I get 2-3 error messages from diagnosis per day.
Where can I find the template/code which creates these records?

**Comment by alexAubin** [comment] 2023-01-27 20:37
The issue is actually already fixed in 11.1 (testing) which is expected to be released around next week so feel free to upgrade to testing ...

corresponding commit : https://github.com/YunoHost/yunohost/commit/70a8225b1de0f9f36d0d8d727e4c218d7ecd30a5

**Closed as completed by alexAubin** 2023-01-27 20:37 UTC

**Comment by renne** [comment] 2023-02-07 10:36
@alexAubin 
I'm sorry to report this bug has not been fixed.
https://github.com/YunoHost/yunohost/commit/70a8225b1de0f9f36d0d8d727e4c218d7ecd30a5 disables the check on the 0/128 value in diagnosis but does not change the wrong value.
The wrong value also causes a DNS update failure at DNS providers like Cloudflare.
I suggest to revert https://github.com/YunoHost/yunohost/commit/70a8225b1de0f9f36d0d8d727e4c218d7ecd30a5 and change the value 128 in the code/template to 0.

**Comment by renne** [comment] 2023-02-07 11:03
@alexAubin 
The wrong "128"-value is in /src/dns.py lines 141 and 251 (dev-branch).
Please replace it with "0" and revert https://github.com/YunoHost/yunohost/commit/70a8225b1de0f9f36d0d8d727e4c218d7ecd30a5.

**Comment by alexAubin** [comment] 2023-02-07 11:18
Hmkay, fixed in https://github.com/YunoHost/yunohost/commit/2eb7da060345e95f10c01f78acbee3b3e35c5739 (I guess it's okay to perform this change now that the diagnosis is okay with both values)

Not sure why 128 is supposed to mean and why we ended up using it in the first place x_x
