### ISSUE TITLE
Useless pull request from yunohost-bot

### ISSUE THREAD

**Issue by jedie** [YunoHost/issues#1797] opened 2021-05-12 15:32 UTC
https://github.com/yunohost-bot made this "autopatch" PR: https://github.com/YunoHost-Apps/pyinventory_ynh/pull/54

He just delete the github action files:

![grafik](https://user-images.githubusercontent.com/71315/118002513-f9354580-b347-11eb-8e2a-cb7a5ec0e63f.png)

The github user page of the bot: https://github.com/yunohost-bot should IMHO list a contact option. Maybe a Link to issues?!?

(Crosspost: https://forum.yunohost.org/t/useless-pull-request-from-yunohost-bot/15748 )

**Comment by tituspijean** [comment] 2021-05-12 15:34
The problem is known, I am quoting @alexAubin here:

> I don't know why my script messed it up ... I will update all the PR later, sorry for the mess

Regarding 
> The github user page of the bot: https://github.com/yunohost-bot should IMHO list a contact option. Maybe a Link to issues?!?

Usually the person triggering the PR via YunoHost-bot is listed as co-author, like in your own PR. 😉

**Comment by jedie** [comment] 2021-05-14 10:10
Next PR: https://github.com/YunoHost-Apps/pyinventory_ynh/pull/56 is there...

It adds **.github/ISSUE_TEMPLATE.md** and **.github/PULL_REQUEST_TEMPLATE.md** ... That's okay.... But still removes my **.github/workflows/package_linter.yml** and **.github/workflows/pytest.yml**

@alexAubin And there is still any contact information missing... What's about to add them in every made PR summary? It should IMHO contain a link to the bot sources and issues tracker...

**Comment by alexAubin** [comment] 2021-08-18 14:24
Sorry about the mess, that edge-case where .github already existed was not taken into account, but could still be fixed by manually handling the use of the new templates

**Closed as completed by alexAubin** 2021-08-18 14:24 UTC
