### ISSUE TITLE
Who is using open ports?

### ISSUE THREAD

**Issue by ericgaspar** [YunoHost/issues#1872] opened 2021-09-10 13:12 UTC
This may already be on the looong TODO list:

in webadmin Outils / Pare-feu  -> add a description of what app/service is using the open ports.

**Comment by alexAubin** [comment] 2021-09-10 19:47
Yup it's a duplicate of https://github.com/YunoHost/issues/issues/1288

**Closed as completed by alexAubin** 2021-09-10 19:47 UTC
