### ISSUE TITLE
backup do not include /home/yunohost.multimedia

### ISSUE THREAD

**Issue by bjarkan** [YunoHost/issues#1461] opened 2019-09-27 20:03 UTC
Maybe sound silly... but some people that use yunohost hold their media in thous folders... why is not included in the backup/restore script... 

An alternative could be to be included in the backup like users... /home/user and /home/yunohost.multimedia 

There are the shared multimedia between users, or just hold private photos, or videos or whatever the user hold it there... 

It's a must, and do not think will be more than a line in the script for backup/restore....

**Comment by zamentur** [comment] 2019-09-27 21:29
I think it's a bit more complex than just add a line in a backup script.

This directory can contain a lot of data (could be >50GB), the admin could want to backup it or not. The native method for backup (with tar.gz) is not a good method for big directory. Borg or archivist are a little more ok with that, but there is a lot of question (like issues around the time to transfer the data, compression/decompression, etc...)

In more the multimedia directory is added by some apps sharing this directory, it's not really integrated in the core of YunoHost, but the issue is app packager don't know if this dir is already backup, so if they add it in their app, they could backup several times the same content !

We need a lot of code to manage all those things around big directory backup management.

Here i list apps using the yunohost.multimedia directory:
- couchpotato (download movies)
- medusa (download tv show)
- transmission (p2p)
- calibreweb (ebooks)
- minidlna (music/video streaming)
- nextcloud (to be able to access multimedia files from nextcloud)
- sickrage (download tv show)
- ampache (music streaming)

Backup every day or week each movies downloaded is a bad idea i think, even with deduplicated backup methods. Do a migration with backup/restore mechanism with a bigger archive than 100GB is a bad idea too.

But i understand there could be some important data in this directory, and nextcloud users could think they should put their multimedia files in this folder as it's called "multimedia"...

Temporarily, we could add a "data_multimedia" backup hooks into the core of yunohost in order to let admin the choice to include it or not. But a lot of users could be suprized and broke their backup system (or even their backup server) if tomorrow we decide to activate this backup by default... So for me it's a bad solution.

May be others have better ideas about this, we should probably discuss it during a meeting.

**Comment by bjarkan** [comment] 2019-09-27 21:44
a tick.... an option to add the multimedia directories... been optional, so the admin of the server decide if in this backup will be included or not... like with home directories.... by the way... by default... not activated... so no one will be disturbed... and the ones that want to have that directory backuped, have the option...

**Comment by bjarkan** [comment] 2019-10-07 12:20
I found a temporary solution.... https://forum.yunohost.org/t/backup-issue-very-important-yunohost-multimedia-not-in-backups/9113

well… i found a use to an unused rasperrypib3… with a terabyte harddisk…

first you need to change the / (root folder) to the external usb harddisk… something very inefficient but very practical in the long run… since sdcards have a limited life…

to do so…

first we need to stop swap
swapoff -a

check the number of the disk… in my case /dev/sda and create a swap partition /dev/sda1 4G (just because i like big swap) and the rest /dev/sda2 in ext4
fdisk -l
fdisk /dev/sda1
partprobe
nano /etc/fstab
add inside
  /dev/sda1 swap swap defaults 0 0
mkswap /dev/sda1
swapon -a

So we go with sda2:
mkfs.ext4 /dev/sda2
mount /dev/sda2 /media

now we need to replicate everything in / (the root of the system in the /dev/sda2 mounted in /media
rsync -ravzxq / /media/

we edit fstab
nano /media/etc/fstab
and add
/dev/sda2 / ext4 defaults 1 1

then we need to go to /boot to edit the command where says where the hell / (root) is
nano /boot/cmdline.txt
root=/dev/sda2

and… dont forget to use this command to be sure that everytime it loads… it check the partition
tune2fs -c 1 /dev/sda2

Once we do that… we can replicate the /home/yunohost.multimedia in that rbpi

rsync -rtpogva --progress --size-only --delete -l -H -partial -b -s /home/yunohost.multimedia/ root@192.168.1.58:/home/backup-multimedia

of course i created /home/backup-multimedia in the rbpi, it’s not fast, but it works and resolv the issue. By the way i used too for holding normal backups…

rsync -rtpogva --progress --size-only --delete -l -H -partial -b -s /home/yunohost.backup/ root@192.168.1.58:/home/backup-backup

I do promise… is very very slow… but works…

**Comment by bjarkan** [comment] 2019-10-07 12:21
By the way... is better to use borg instead of classic rsync for backups....

**Comment by zamentur** [comment] 2021-09-22 14:17
Close the ticket cause it's fixed by https://github.com/YunoHost/yunohost/blob/dev/data/hooks/backup/18-data_multimedia

**Closed as completed by zamentur** 2021-09-22 14:17 UTC
Labels: :ambulance: Backup
