### ISSUE TITLE
Cannot log into YunoHost or into any app

### ISSUE THREAD

**Issue by xplosionmind** [YunoHost/issues#1959] opened 2022-01-07 10:22 UTC
### Describe the bug

I see this page whenever I try to log into any of my apps. After submitting the correct credentials, nothing changes, and not even an error message appears.

<img width="1440" alt="Screenshot 2022-01-07 at 11 16 03 AM" src="https://user-images.githubusercontent.com/42862428/148529319-d0b738ab-94eb-4543-8e3c-672bc662c246.png">

Furthermore, the login page is not formatted correctly. The CSS files are not found:

<img width="1440" alt="Screenshot 2022-01-07 at 11 20 42 AM" src="https://user-images.githubusercontent.com/42862428/148529710-b01169ae-6ead-4807-8e34-c48f3bb3f206.png">

### Context

- Hardware: *Contabo VPS*
- YunoHost version: *4.3.5*
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### To reproduce

- visit the YunoHost URL, or the one of any of the installed apps;
- try to log in.

### Expected behavior

Logging in normally and seeing the page normally.

### Logs

In the diagnosis, everything appears to be normal, even after rebooting.

**Comment by alexAubin** [comment] 2022-11-20 17:52
Closing because don't know how to reproduce ... From the screenshot I can see that the CSS assets are being taken from the cache I think ? (302) and weigh 0 bytes ... I guess a force-refresh of the browser may fix the issue ... Or at least I guess you somehow found a fix since then ...

**Closed as completed by alexAubin** 2022-11-20 17:52 UTC
