### ISSUE TITLE
Redirect loop because of make default script

### ISSUE THREAD

**Issue by Aeris1One** [YunoHost/issues#1542] opened 2020-04-01 13:51 UTC
Hi,
I have a redirect loop on my domain (aerispad.rdm).
Here what I did : 
- Bugued my Etherpad instance.
- Reinstalled it on aerispad.rdm/pad
- Make it default (so aerispad.rdm redirects to aerispad.rdm/pad)
- Moved Etherpad (aerispad.rdm/pad => aerispad.rdm)
- Notice that the domain root is still redirecting to /pad.
- Make Etherpad default (so aerispad.rdm redirects to aerispad.rdm)
- You have a working Redirect Loop !

But now I don't know how to remove the redirect loop -_-
Does anyone know how to make an app non-default ? (That way aerispad.rdm will not redirect anymore)

I tried `sudo yunohost app ssowatconf` and `sudo yunohost tools regen-conf`, no effect.

Does anyone have a clue?

**Comment by Aeris1One** [comment] 2020-04-01 18:47
I neither found something strange in nginx's domain config, nor in ssowat's config...

**Comment by alexAubin** [comment] 2020-04-28 02:44
It's in /etc/ssowat/conf.json.persistent ... The "makedefault" code is a huge hack and should be reworked, c.f. https://github.com/YunoHost/issues/issues/40

Unfortunately it's not clear how to handle this properly. Naively could be done using a setting in the app, or a setting about the domain, but gotta be careful about tricky edge cases like app_changeurl or backup/restore... Naively I'd use a domain setting but we don't have those yet.

**Comment by alexAubin** [comment] 2020-04-30 12:36
Note that it should not be possible in recent 3.7.x because Yunohost will refuse to make default an app if it's already on the root (this was a regression in previous version of 3.7)

**Comment by Aeris1One** [comment] 2020-05-01 08:43
I'll keep this issue open until the code is reworked.

**Comment by alexAubin** [comment] 2020-08-26 16:23
Closing because that should be fixed now ...

**Closed as completed by alexAubin** 2020-08-26 16:23 UTC
