### ISSUE TITLE
Allow Let's encrypt wildcard subdomain certificates in CAA records

### ISSUE THREAD

**Issue by renne** [YunoHost/issues#2128] opened 2023-01-13 14:58 UTC
### Describe the bug

The CAA DNS resource records suggested by Yunohost/created by the autodns feature include only an "issue" statement for single subdomain certificates. A strict implementation must not create wildcard certificates.

### Context

- Hardware: Proxmox KVM on bare metal
- YunoHost version: 11.0.11
- I have access to my server: Through SSH | direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### To reproduce

Go to the DNS settings of a domain and view the suggested DNS CAA resource records -> no "issuewild" statement.

### Expected behavior

The suggested CAA-RRs should contain an "issuewild" statement to allow the creation of wildcard subdomain certificates.

**Comment by tituspijean** [comment] 2023-01-14 14:49
Related to https://github.com/YunoHost/issues/issues/2089

**Comment by renne** [comment] 2023-02-08 05:11
@alexAubin 
@tituspijean 
Just add additional CAA resource records in /src/dns.py lines 141 and 251 (dev-branch) with the "issuewild" tag.
It is the same record like the "issue" tag:
```
;; CAA Records
example.com.	3600	IN	CAA	0 issue     "letsencrypt.org"
example.com.	3600	IN	CAA	0 issuewild "letsencrypt.org"
```
After that change Let's Encrypt wildcard-certificates can be requested via the DNS-challenge.

**Comment by alexAubin** [comment] 2024-10-22 16:18
Closing as duplicate of https://github.com/YunoHost/issues/issues/2089, there's no point in having this specific sub-issue, the main technical challenge is integrating the DNS-based challenge in YunoHost like we did for the HTTP-based ACME challenge, which is required for wildcard certs, and changing the logistic to use certificates for subdomains etc

**Closed as not planned by alexAubin** 2024-10-22 16:18 UTC
Labels: :globe_with_meridians: DNS
