### ISSUE TITLE
Apps deleted after update/upgrade

### ISSUE THREAD

**Issue by isAAAc** [YunoHost/issues#1231] opened 2018-11-05 15:28 UTC
Opensondage, Mattermost, Dokuwiki ont disparus suite à la commande : 
`yunohost tools update && yunohost tools upgrade && yunohost app upgrade`

How to get my apps back with correct data please ?
How to patch this ?

here's the full log :
 https://krashboyz.org/zerobin/?5bc29bbdac378a61#Z0pxgzwyIx5acu1NR+t9YQJfCsELqyoHTCsnlPJ/EHc=

Thx a lot for your Help

**Comment by isAAAc** [comment] 2018-11-05 17:17
resolved for Opensondage && Mattermost after rm -Rf /etc/nginx/conf.d/<an_old_ndd_freshly_removed>, and then restore apps is ok, 
but i still have trouble to restore Dokuwiki .

so there are still 3 questions : 

- why /etc/nginx.conf.d/<old_ndd> was still here after the remove of the ndd ?
- why the nginx message break the upgrade process ?
- why Dokuwiki has a special trouble after rm the nginx folder ?


 
f

**Comment by Gofannon** [comment] 2018-11-05 17:29
Hello,

( My opinion : I am not sure if Github is the best place to discuss about this issue. Maybe the forum will be helpful as there is more people there : http://forum.yunohost.org/ )

- Did you also update also other apps ? (I only have a look for Dokuwiki specifically)
- How it went ?
- Can you try to see if you have backups on your server by looking here : https://yunohost.org/#/backup
- Do you have a recent backup of your data?
- Do you remember messing with setting `backup_core_only` ?
- Can you provide output of theses commands ? "systemctl status nginx.service" and "journalctl -xe"
- can you provide output of `yunohost log display 20181104-225744-backup_restore_app-dokuwiki --share`


## Dokuwiki log analyze

I will only look for Dokuwiki and will detail what the commands why typed made on dokuwiki

### Upgrade - prebackup
- Line 255 : while upgrading, Yunohost attempted to make a backup just in case something breaks (which happened)
- L327 : `2018-11-04 22:57:17,618 WARNING  yunohost.hook <lambda> - [19422.1] /var/www/dokuwiki will not be saved, because backup_core_only is set.`
  This settings tells Yunohost to not backup your data and imply that you have to do it by yourself
- L336 : `2018-11-04 22:57:17,621 DEBUG    yunohost.hook <lambda> - [19422.1] + echo '/var/www/dokuwiki will not be saved, because backup_core_only is set.'`
  Confirmation of above

### Upgrade - resume after backup

- L590-596 : nginx failed to restart after upgrade

```
2018-11-04 22:57:27,314 DEBUG    yunohost.hook <lambda> - [16905.1] + sudo systemctl reload nginx
2018-11-04 22:57:29,419 WARNING  yunohost.hook <lambda> - [16905.1] Job for nginx.service failed because the control process exited with error code.
2018-11-04 22:57:29,423 WARNING  yunohost.hook <lambda> - [16905.1] See "systemctl status nginx.service" and "journalctl -xe" for details.
2018-11-04 22:57:29,524 DEBUG    yunohost.hook <lambda> - [16905.1] + ynh_exit_properly
2018-11-04 22:57:29,524 WARNING  yunohost.hook <lambda> - [16905.1] !!
2018-11-04 22:57:29,524 DEBUG    yunohost.hook <lambda> - [16905.1] + local exit_code=1
2018-11-04 22:57:29,525 WARNING  yunohost.hook <lambda> - [16905.1]   dokuwiki's script has encountered an error. Its execution was cancelled.```


**[some steps missing - lack of time]**

### Restore as upgrade failed

Yunohost restores the upgrade made before upgrading but it fails too

- L881 `2018-11-04 22:57:53,018 INFO     yunohost.log close - [19659.1] The operation 'Restore 'dokuwiki' from a backup archive' has failed ! To get help, please share the full log of this operation using the command 'yunohost log display 20181104-225744-backup_restore_app-dokuwiki --share'`

**Comment by isAAAc** [comment] 2018-11-05 21:10
> Hello,
hi ;)

>     * Did you also update also other apps ? (I only have a look for Dokuwiki specifically)
yep as said, Opensondage, Mattermost, Dokuwiki  have gone

>     * How it went ?
as said , during a `yunohost tools update && yunohost tools upgrade && yunohost app upgrade`

>     * Can you try to see if you have backups on your server by looking here : https://yunohost.org/#/backup
```
/home/yunohost.backup/archives# ls -al |grep dokuwiki
-rw-r--r-- 1 root root        341 nov.   4 22:57 dokuwiki-pre-upgrade1.info.json
-rw-r--r-- 1 root root    8100024 nov.   4 22:57 dokuwiki-pre-upgrade1.tar.gz
```
>     * Do you have a recent backup of your data?
looks like

>     * Do you remember messing with setting `backup_core_only` ?
nope

>     * Can you provide output of theses commands ? "systemctl status nginx.service" and "journalctl -xe"

```
/home/yunohost.backup/archives# systemctl status nginx.service
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2018-11-05 17:46:57 CET; 4h 14min ago
     Docs: man:nginx(8)
  Process: 29981 ExecReload=/usr/sbin/nginx -g daemon on; master_process on; -s reload (code=exited, status=0/SUCCESS)
 Main PID: 11339 (nginx)
    Tasks: 4 (limit: 4915)
   Memory: 59.4M
      CPU: 40.524s
   CGroup: /system.slice/nginx.service
           ├─11339 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
           ├─29096 nginx: worker process is shutting down
           ├─29983 nginx: worker process
           └─29984 nginx: worker process
```
```
/home/yunohost.backup/archives# journalctl -xe
nov. 05 22:02:00 krashboyz mysqld[1715]: 2018-11-05 22:02:00 7f7ff8d6e700 InnoDB: Error: Column last_update in table "mysql"."innodb_table_stats" is INT UNSIGNED NOT NULL but should be BINAR

```
many lines like this one ^

>     * can you provide output of `yunohost log display 20181104-225744-backup_restore_app-dokuwiki --share`

 This log is now available via https://paste.yunohost.org/raw/zepawerodi



> ## Dokuwiki log analyze
> 
> I will only look for Dokuwiki and will detail what the commands why typed made on dokuwiki
> ### Upgrade - prebackup
> 
>     * Line 255 : while upgrading, Yunohost attempted to make a backup just in case something breaks (which happened)
> 
>     * L327 : `2018-11-04 22:57:17,618 WARNING  yunohost.hook <lambda> - [19422.1] /var/www/dokuwiki will not be saved, because backup_core_only is set.`
>       This settings tells Yunohost to not backup your data and imply that you have to do it by yourself
> 
>     * L336 : `2018-11-04 22:57:17,621 DEBUG    yunohost.hook <lambda> - [19422.1] + echo '/var/www/dokuwiki will not be saved, because backup_core_only is set.'`
>       Confirmation of above

Damn ... why is it set like this ?
How/where can i  change this setting ?

i suppose my old dokuwiki is completely lost ?
> 
> ### Upgrade - resume after backup
> 
>     * L590-596 : nginx failed to restart after upgrade

yes as i said, the were some undeleted data as they wich should be after a ndd revocation, i did it manually, nginx is ok now, the other apps are restored, only dokuwiki doesn't.

**Comment by maniackcrudelis** [comment] 2018-11-05 23:02
Looks like it's an old and buggy version of the backup script https://github.com/YunoHost-Apps/dokuwiki_ynh/commit/feba478177fdb78c9e55fc1e9b6d646e5532f977#diff-dab29616182e947d2761d52c308b0d60, especially with `ynh_backup "$final_path" "sources" 1`. Which is why `/var/www/dokuwiki` is missing in the last backup.
If you don't have any other backup of your app, I'm afraid there's nothing to do to get back your data, as Dokuwiki seems to not use a database.
Sorry for that...

About the failure of the upgrade, it could be interesting to have a look to nginx log, `/var/log/nginx/error.log` at 2018-11-04 22:57:29 to understand why nginx failed to reload.

**Comment by isAAAc** [comment] 2018-11-06 14:44
> I'm afraid there's nothing to do to get back your data

yes i think it's dead

>About the failure of the upgrade, it could be interesting to have a look to nginx log, /var/log/nginx/error.log at 2018-11-04 22:57:29 to understand why nginx failed to reload.
```
/var/log/nginx# zmore error.log.2.gz
2018/11/04 22:57:27 [emerg] 19541#19541: BIO_new_file("/etc/yunohost/certs/stream.krashboyz.org/crt.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/yunohost/certs/stream.krashboyz.org/crt.pem'
,'r') error:2006D080:BIO routines:BIO_new_file:no such file)
2018/11/04 22:57:38 [emerg] 19645#19645: BIO_new_file("/etc/yunohost/certs/stream.krashboyz.org/crt.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/yunohost/certs/stream.krashboyz.org/crt.pem'
,'r') error:2006D080:BIO routines:BIO_new_file:no such file)
```
was old garbage datas i deleted later manually as said

i need to read the backup documentation again to verify all my apps and data are well backuped , 

i think this issue can be close

**Comment by Gofannon** [comment] 2018-11-09 14:36
> yes i think it's dead

Well, I hope it will be fine...

> was old garbage datas i deleted later manually as said
> 
> i need to read the backup documentation again to verify all my apps and data are well backuped ,
> 
> i think this issue can be close

How did you add these files? Using a Yunohost application or manually?
Yunohost backup system depends on code made by application packager. In your case, there was a bug in the backup script so even if you though that you had backup up, you hadn't ...

@maniackcrudelis, it might be better to revert the new version as other people might loose data? (Because of a problem with an other app on their system)
Second ticket https://github.com/YunoHost-Apps/dokuwiki_ynh/issues/32#issuecomment-437341318

And then spit the upgrade in two deliveries (if it's possible) : push the new backup script then the whole upgrade.
Or maybe, upgrade only the "Yunohost package code" without modifying "dokuwiki app code."

**Comment by maniackcrudelis** [comment] 2018-11-09 20:52
The problem isn't really about the upgrade script but more about the backup script.
A thing which could be done is to check the version of the package and disable the backup for this (or theses ?) buggy version(s) as well as the remove and restore during the backup.

**Comment by Gofannon** [comment] 2018-11-16 16:45
> The problem isn't really about the upgrade script but more about the backup script.
> A thing which could be done is to check the version of the package and disable the backup for this (or theses ?) buggy version(s) as well as the remove and restore during the backup.

I was thinking about the process of "upgrading an app" and not about a script itself

Where and who should do these checks? On the app side or on the yunohost core?
Maybe putting a flag in the manifest could do to ask which scripts should be used ("existing app" or "upgraded app")

I guess the discussion should involve more people. Any idea of a place to discuss this ? Forum or https://github.com/YunoHost/issues/issues ?

**Comment by alexAubin** [comment] 2021-10-03 21:03
Closing because the issue is pretty old, nowadays the are failsafe to prevent miserably uninstalling all apps if one upgrade fails, and generally speaking stuff are more robust

**Closed as completed by alexAubin** 2021-10-03 21:03 UTC
