### ISSUE TITLE
Generating Let's Encrypt certificates fails when doing it for a fresh-new domain that has proper DNS records

### ISSUE THREAD

**Issue by KamilBaczkowski** [YunoHost/issues#1846] opened 2021-08-09 13:20 UTC
### Describe the bug

When I add a new domain, I can't generate a Let's Encrypt cert for it, the admin panel complains that some things are misconfigured, and I have to check the diagnosis page.
After running the diagnosis, it turns out that everything is okay when it comes to the DNS records for that domain, and then I can generate the cert.

### Context

- Hardware: VPS bought online
- YunoHost version: 4.2.6.1
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
 - Some configuration to postfix regarding catch-all email addresses

### Steps to reproduce

- Add a new domain that has a proper DNS configuration
- Go to the domain's settings
- Try to generate a Let's Encrypt certificate
- The web admin complains that some issues have to be resolved beforehand.

### Expected behavior

I should be able to generate a Let's Encrypt cert on the first try. 
Alternatively, since running the diagnosis in the background is resource intensive (full diagnosis takes some time on my server, so it may be), instead of showing a text that there are some issues with the DNS configuration, an information that the diagnosis has to be run before trying to set up the certificate would be welcomed. The first time I encountered that, I have run diagnosis multiple times trying to figure out what exactly is wrong, and then it turned out everything was okay.

### Logs

https://paste.yunohost.org/raw/elaporayaf
NOTE: there is a warning in the logs that one of the files has been modified. It is indeed the case, but the issue was reproducible even before the modifications.

**Comment by frju365** [comment] 2021-08-09 14:01
The fact that you have to do a diagnose before generating cert is indeed perhaps not clear. But you explained it. For me it's not a bug but indeed warning must have more clear explanations, about the fact that doing a diagnos before begining the generation process is needed.

(this check is needed to prevent ban from let's encrypt for having tried more than 5 times to have a cert).

**Comment by KamilBaczkowski** [comment] 2021-08-09 14:03
In that case, the wording should be changed. I know that YH can run only one step of the diagnosis, so maybe running DNS checks could be incorporated into the new domain setup process?

**Comment by alexAubin** [comment] 2022-11-20 16:42
Closing because duplicate of https://github.com/YunoHost/issues/issues/1634

**Closed as completed by alexAubin** 2022-11-20 16:42 UTC
