### ISSUE TITLE
[enh] automatic backups with rotation

### ISSUE THREAD

**Issue by nqb** [YunoHost/issues#1268] opened 2019-01-09 06:31 UTC
Hello,

It will be nice to have a script that do a complete backup of YunoHost with a rotate function that delete old backups. This script should be call by `cron` and should check **before** running backups if they are enough size on disk to do a complete backup. In case of not enough size, it should warn admin user of YunoHost.

**Comment by nqb** [comment] 2019-01-17 13:19
The first part of this script do something equivalent:

https://github.com/inverse-inc/packetfence/blob/devel/addons/database-backup-and-maintenance.sh

**Comment by Psycojoker** [comment] 2019-02-06 19:37
Ah, not especially, I know that `du -hc` can do that, `ncdu` is an interact version or simply `ls -l`.

I know there is often a conflict between the actual size of files and the effectively used space because a lot of small files can take more place than a single big file because of the inodes usage.

**Comment by nqb** [comment] 2019-02-06 20:24
When I said:

> Do you know which command I can run on the FS to get the size of a complete backup ?

I want to know **where** I should run this command to get the size of a complete backup as run by `yunohost backup create`

**Comment by zamentur** [comment] 2019-02-06 22:50
I think it's possible to run a dry run backup. you just need to specify no method, or a method that do nothing.

But the size you will get is the size of the data, and not the compressed size or the size of the deduplicated data in the borg case...

**Comment by zamentur** [comment] 2021-09-22 14:22
Duplicate of https://github.com/YunoHost/issues/issues/835

**Closed as completed by zamentur** 2021-09-22 14:22 UTC
Labels: Help wanted, :ambulance: Backup, :bangbang: Priority: high
