### ISSUE TITLE
Migration 4.4. to 11.x. fails; -> "Error: Command 'wget ..."

### ISSUE THREAD

**Issue by AkselRocks** [YunoHost/issues#2070] opened 2022-09-18 12:52 UTC
### Describe the bug

Migration 4.4. to 11.x. fails

ERROR - Migration 0021_migrate_to_bullseye did not complete, aborting. Error: Command 'wget -O- https://forge.yunohost.org/yunohost_bullseye.asc -q | apt-key add -qq -' returned non-zero exit status 2.

### Context

- Hardware: VPS bought online 
- YunoHost version: 4.4.2.14
- I have access to my server: Through SSH 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - If yes, please explain: changed sshd_config
- If upgrading, current YunoHost version: 4.4.2.14

### To reproduce
- 
    ```sh
    yunohost tools migrations run --accept-disclaimer
    ```

### Expected behavior

migration to 11.x.

### Logs
see https://paste.yunohost.org/raw/qemiruveyi

**Comment by tituspijean** [comment] 2022-09-18 13:35
Can you try running the command manually, with more verbosity?

`wget -O- https://forge.yunohost.org/yunohost_bullseye.asc | apt-key add  -`

**Comment by AkselRocks** [comment] 2022-09-18 13:41
```
wget -O- https://forge.yunohost.org/yunohost_bullseye.asc | apt-key add -
--2022-09-18 15:39:32--  https://forge.yunohost.org/yunohost_bullseye.asc
Resolving forge.yunohost.org (forge.yunohost.org)... 80.67.172.144, 2001:910:1410::1
Connecting to forge.yunohost.org (forge.yunohost.org)|80.67.172.144|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2456 (2.4K) [application/octet-stream]
Saving to: ‘STDOUT’

-                        100%[==================================>]   2.40K  --.-KB/s    in 0s      

2022-09-18 15:39:32 (212 MB/s) - written to stdout [2456/2456]

gpg: [don't know]: invalid packet (ctb=23)
gpg: keydb_get_keyblock failed: Value not found
gpg: [don't know]: invalid packet (ctb=23)
gpg: /tmp/apt-key-gpghome.R7ut2aZ3bi/pubring.gpg: copy to '/tmp/apt-key-gpghome.R7ut2aZ3bi/pubring.gpg.tmp' failed: Invalid packet
gpg: error writing keyring '/tmp/apt-key-gpghome.R7ut2aZ3bi/pubring.gpg': Invalid packet
gpg: error reading '-': Invalid packet
gpg: import from '-' failed: Invalid packet
```

**Comment by AkselRocks** [comment] 2022-10-16 17:32
ping.
Anybody any idea?

**Comment by alexAubin** [comment] 2022-11-20 21:07
Closing because meh, can't reproduce the issue, it look like your gpg setup is broken ...

**Closed as completed by alexAubin** 2022-11-20 21:07 UTC
