### ISSUE TITLE
Install robots.txt

### ISSUE THREAD

**Issue by Salamandar** [YunoHost/issues#2491] opened 2024-11-25 13:51 UTC
Prevent stuff like that

![image](https://github.com/user-attachments/assets/770587e5-7e2f-4ea2-8b61-3912a3668b4e)

by installing a robots.txt per domain.

**Comment by alexAubin** [comment] 2024-11-25 14:02
Duplicate of https://github.com/YunoHost/issues/issues/2361

**Closed as not planned by alexAubin** 2024-11-25 14:02 UTC
