### ISSUE TITLE
Error 500 GET /yunohost/api/apps/my_web__2/config?full&locale=en

### ISSUE THREAD

**Issue by kjharcombe** [YunoHost/issues#2144] opened 2023-02-09 22:03 UTC
### Describe the bug

Yunohost webadmin is outputting 
`Error 500`
`GET /yunohost/api/apps/my_webapp__2/config?full&locale=en`
when attempting to access the configuration panel for my_webapp__2
### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.1.6
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain:
- Using, or trying to install package version/branch:
- If upgrading, current YunoHost version: 

### To reproduce

1. I created a custom web app using the 'my_webapp'
2. Went to the configuration panel for my_webapp and got error message shown in screenshot below.

### Logs

https://paste.yunohost.org/raw/suyavaguzu
![Screenshot 2023-02-09 at 21 53 21](https://user-images.githubusercontent.com/76237554/217948808-c4d9b35a-f0e8-4491-a8da-7a5918750830.png)

**Comment by alexAubin** [comment] 2023-02-09 22:07
Duplicate of https://github.com/YunoHost-Apps/my_webapp_ynh/issues/97 , fix on its way in https://github.com/YunoHost-Apps/my_webapp_ynh/pull/106

**Closed as completed by alexAubin** 2023-02-09 22:07 UTC
