### ISSUE TITLE
Cleanup after domain removal

### ISSUE THREAD

**Issue by Salamandar** [YunoHost/issues#1629] opened 2020-06-09 15:46 UTC
I created a domain then deleted it. The domain name was `auie.fr`. Some files are left in the filesystem : 
```
/var/log/nginx/rauie.fr-error.log
/var/log/nginx/rauie.fr-access.log
/var/log/yunohost/categories/operation/*
/var/www/.well-known/rauie.fr
/etc/dkim/rauie.fr.mail.txt
/etc/dkim/rauie.fr.mail.key
/etc/nginx/conf.d/rauie.fr.d
/etc/yunohost/certs/rauie.fr-history
```
I understand that the log should stay ; but what about the DKIM and nginx config ?

**Comment by scharc** [comment] 2020-10-14 19:13
I had the issue that it did not clean up dnsmasq entries (/etc/dnsmasq.d/[DOMAIN])

**Comment by Neustradamus** [comment] 2021-08-15 13:05
@alexAubin : Have you progressed on this bug?

**Comment by alexAubin** [comment] 2022-11-20 13:44
Duplicate of https://github.com/YunoHost/issues/issues/1522

**Closed as completed by alexAubin** 2022-11-20 13:44 UTC
