### ISSUE TITLE
Firewall could also reveal service names in port listing

### ISSUE THREAD

**Issue by jose1711** [YunoHost/issues#2034] opened 2022-07-07 08:28 UTC
Think it would be nice to see the reason why a certain port is opened in firewall.
![obrázok](https://user-images.githubusercontent.com/1406222/177727989-7c3f5700-f4fd-43e6-a14d-fd6cc33edf54.png)

Maybe the table could include another column: Service. And perhaps an extra user-editable column (comment) that could contain an information why a specific port is closed/opened would be useful too.

**Comment by alexAubin** [comment] 2022-11-20 20:03
Duplicate of https://github.com/YunoHost/issues/issues/1288

**Closed as completed by alexAubin** 2022-11-20 20:03 UTC
Labels: :maple_leaf: Web administration, :star2: UX
