### ISSUE TITLE
Separate API and command line definitions

### ISSUE THREAD

**Issue by Salamandar** [YunoHost/issues#2500] opened 2024-12-13 09:42 UTC
We are accessing the limits of what Moulinette allows for combined API / CLI definitions. We might want to provide more powerful APIs for the webadmin while not cluttering the command line.

Also the command line, in its current state, has some drawbacks:
* it restarts a whole instance of YunoHost's code, so it's kinda slower than the already-running API daemon
* having multiple instances of YunoHost's code prevents some data caching / better lock management
* we always need to run it as `root`, so it's a broader attack surface

The API has also some drawbacks of its own, linked to moulinette. 

Here's a suggestion :
* YunoHost-API could expose its API on a unix socket that wouldn't require authentication ("logged in by default")
* This socket would be only accessible by users in the `yunohost-admin` group (or just `admins`)
* The command line would just be a client of this API

So, in order :
- [ ] Modify YunoHost to expose an unauthenticated API on a unix socket
- [ ] write a yunohost-api-cmdline tool that would keep compat with the current cmdline
- [ ] once that's done we can use something else that `moulinette` to expose the API.

**Comment by Axolotle** [comment] 2024-12-13 09:46
kinda duplicate of https://github.com/YunoHost/issues/issues/2430

**Comment by Salamandar** [comment] 2024-12-13 09:51
gmpffpf i searched for something like it but could not find it. Closing and commenting there.

**Closed as completed** 2024-12-13 09:51 UTC
Labels: :construction: Refactoring, :building_construction: Major project
