### ISSUE TITLE
Feature allowing users to register on YunoHost

### ISSUE THREAD

**Issue by tdlf32** [YunoHost/issues#2141] opened 2023-02-04 13:48 UTC
Hello, I'm a long time Yunohost user and I'm very happy with it, but I find that it lacks a necessary feature to this tool, that is to allow users to register and create their accounts themselves. This solution could allow us to use YunoHost to host sites that require user registration. This would also allow us to take advantage of Yunohost's SSO!

Even using a personal YunoHost cloud as a family, I am forced to create my relatives' accounts one by one, which is very limiting :/

Do you have any idea of a release date for this feature?

**Comment by tituspijean** [comment] 2023-02-04 14:00
Duplicate of #1677.

**Closed as not planned** 2023-02-04 14:00 UTC
