### ISSUE TITLE
Not information on failed post-install while using install.yunohost.org

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1166] opened 2018-07-22 06:50 UTC
I've been running `curl install.yunohost.org | bash` on a fresh stretch debian vps and answered yes to every question.

At the end, he asked me if I wanted to do the post-installation, I answer yes, he then told me that the post-installation failed whitout telling me WHY and asked me if I wanted to retry, same result.

We should display why the post-installation failed, it's not even written down in the log :|

End of the log of the post-installation:

```
Created symlink /etc/systemd/system/default.target.wants/yunoprompt.service → /etc/systemd/system/yunoprompt.service.
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
Created symlink /etc/systemd/system/multi-user.target.wants/yunohost-api.service → /lib/systemd/system/yunohost-api.service.
Setting up yunohost-admin (3.0.0) ...
Setting up libwww-perl (6.15-1) ...
Setting up liblwp-protocol-https-perl (6.06-2) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Processing triggers for systemd (232-25+deb9u4) ...
Processing triggers for resolvconf (1.79) ...
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
Processing triggers for rsyslog (8.24.0-1) ...
Processing triggers for php7.0-fpm (7.0.30-0+deb9u1) ...
Processing triggers for dbus (1.10.26-0+deb9u1) ...
W: --force-yes is deprecated, use one of the options starting with --allow instead.
[INFO] Running restart_services
[INFO] Running post_install
[FAIL] Post-installation failed
[INFO] Installation logs are available in /var/log/yunohost-installation_20180722_083421.log
```

The file `/var/log/yunohost/yunohost-api.log` is empty but `/var/log/yunohost/yunohost-cli.log` contains some useless stuff:

```
2018-07-22 08:38:39,156 DEBUG    moulinette.actionsmap __init__ - loading actions map namespace 'yunohost'
2018-07-22 08:38:39,166 DEBUG    moulinette.actionsmap __init__ - extra parameter classes loaded: ['ask', 'password', 'required', 'pattern']
2018-07-22 08:38:39,180 DEBUG    moulinette.interface __init__ - initializing base actions map parser for cli
2018-07-22 08:38:39,181 DEBUG    moulinette.interface __init__ - registering new callback action 'yunohost.utils.packages.ynh_packages_version' to ['-v', '--version']
2018-07-22 08:38:39,214 ERROR    yunohost cli - Opération interrompue
2018-07-22 08:38:43,130 DEBUG    moulinette.actionsmap __init__ - loading actions map namespace 'yunohost'
2018-07-22 08:38:43,137 DEBUG    moulinette.actionsmap __init__ - extra parameter classes loaded: ['ask', 'password', 'required', 'pattern']
2018-07-22 08:38:43,137 DEBUG    moulinette.interface __init__ - initializing base actions map parser for cli
2018-07-22 08:38:43,138 DEBUG    moulinette.interface __init__ - registering new callback action 'yunohost.utils.packages.ynh_packages_version' to ['-v', '--version']
2018-07-22 08:38:43,170 ERROR    yunohost cli - Opération interrompue
```

I've attached the SUPER LONG full installation log to this post : [failed_installation_log.txt](https://github.com/YunoHost/issues/files/2216764/failed_installation_log.txt)

**Comment by alexAubin** [comment] 2018-08-15 14:37
We can't use `curl install.yunohost.org | bash` because of the way stdin isn't available or can't be propagated to the post-install command at the end of the script.

So currently that's the expected behavior, and the documentation says to use `bash <(wget -q -O- https://install.yunohost.org/)` ...

Either we are happy with this, or either we need to manage some magic to be able to have stdin available by the postinstall command. Or we can also decide to just tell the user to run `yunohost tools postinstall` (or go to the webadmin), which to me is no big deal and is a 10-seconds fix.

**Comment by alexAubin** [comment] 2018-12-19 23:36
Indirectly fixed via https://github.com/YunoHost/install_script/pull/54

**Closed as completed by alexAubin** 2018-12-19 23:36 UTC
Labels: :rocket: Installation, :star2: UX, :bangbang: Priority: high
