### ISSUE TITLE
Register visitor accounts

### ISSUE THREAD

**Issue by tdlf32** [YunoHost/issues#2190] opened 2023-04-18 21:34 UTC
Hello, Is it possible for a visitor to register an account on Yunohost?

If this is not a built-in feature of Yunohost, then how can I do it?

**Comment by tituspijean** [comment] 2023-04-19 09:45
Duplicate of https://github.com/YunoHost/issues/issues/1677

The matter is highly technical and touches core features of YunoHost, you most likely cannot do it yourself.

**Closed as not planned by tituspijean** 2023-04-19 09:45 UTC
Labels: Bingo

**Comment by tdlf32** [comment] 2023-04-19 22:34
Thank you for your answer
Is this feature planned in YunoHost?
