### ISSUE TITLE
Per user customization for Portal

### ISSUE THREAD

**Issue by Agwebberley** [YunoHost/issues#2024] opened 2022-06-21 22:23 UTC
# Problem
Currently the Dashboard is completely not customization for the user and can only be edited globally.  

# Proposal 
- Each user has a file that contains all of their settings (JSON or YAML?)
- Not all users are going to use all of the apps in some cases, as part of the settings can be what apps they want to see in the main dashboard and there is a list of all apps that allows them to check which ones that they want.
- Background and color theme should be allowed to change per user
- Admin area should be able to change the default background and switch icon without having to ssh in and edit code.

**Comment by tituspijean** [comment] 2022-06-22 10:10
Duplicate of https://github.com/YunoHost/issues/issues/1848.

**Closed as not planned by tituspijean** 2022-06-22 10:10 UTC
