### ISSUE TITLE
Be able to remove directly a user from a permission (3.7 testing)

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#1428] opened 2019-09-03 12:24 UTC
I wanted to remove a user from a permission, and i can't do it directly with
```
$ yunohost user permission remove mail -u test
Error: You need to redefine the permission using 'yunohost user permission add -u USER' before removing an allowed group
```
Cause i am in the default state (like after `yunohost user permission clear mail`)... It's quite annoying to have to define manually all users or groups with `yunohost user permission add mail -u USER1 USER2`

Is there a reason i don't understand ?
May be we could make the add automatically qith all the user until the one that has been removed ?

Note i have no idea for the IHM in Webadmin for this usecase...

**Comment by Josue-T** [comment] 2019-09-03 12:32
Well, the problem is that we have a special group "all_user" which contains all user and it's the default group used for the permission. So the solution could maybe be to add all user to the permission.

I also would say how it worked and I just reproduced this concept.

You can more understand how it work [here](https://moulinette.readthedocs.io/en/latest/ldap.html#ldap-architecture-in-yunohost)

**Comment by zamentur** [comment] 2019-09-03 12:43
I already know how it works for the all_users group, and i understand why it's made like that, but on the ux side it's not ideal.

And i just thinking it could create a regression in user xp, what if the user on webadmin receive this message during the use of old permission feature. I classify this ticket in bug, due to this regression (note the webadmin permission part seems not working anymore at all, i will create a specific ticket or a bugfix for webadmin part)

**Comment by Josue-T** [comment] 2019-09-03 12:57
> i understand why it's made like that, but on the ux side it's not ideal.

Yes I think too that It could create some confusion.

> And i just thinking it could create a regression in user xp

I don't understand because precisely tried to reproduce the old mechanism.

> (note the webadmin permission part seems not working anymore at all, i will create a specific ticket or a bugfix for webadmin part)

Ok, so are you working on that ?

**Comment by zamentur** [comment] 2019-09-04 11:22
Yep i am working on webadmin

**Comment by alexAubin** [comment] 2019-11-25 15:38
Closing because that's kinda fixed since then ... (and we ain't gonna add an exclude mechanism I think)

**Closed as completed by alexAubin** 2019-11-25 15:38 UTC
Labels: :busts_in_silhouette: User management, :star2: UX
