### ISSUE TITLE
Changing main domain result in redirection error

### ISSUE THREAD

**Issue by ImaCrea** [YunoHost/issues#1343] opened 2019-04-25 15:14 UTC
# Context
Just after fresh manual install of Yunohost on Debian 9.8 AMD 64 on Macbook 3,1.
# Steps to reproduce bug 
- set xxx.com as domain on postinstall process
- all working fine
- add a new domain yyy.com as domain
- set yyy.com as main domain
- remove xxx.com domain
- go to yyy.com and see browser redirected to xxx.com hence server not reachable.

It happens also if first domain set is a xxx.nohost.me kind of domain.

# Note
Only solution I found is to re-install the whole thing.
Tested with browser in private mode, this is not a browser cache issue.

**Comment by Psycojoker** [comment] 2019-05-08 19:42
It is possible that this is an issue related to browser caching redirection (but that needs to be confirmed).

**Comment by ImaCrea** [comment] 2019-05-14 15:58
Nope, check the bottom note in my issue :)

**Comment by alexAubin** [comment] 2020-04-28 03:46
I think that's related to [this stupid piece of code](https://github.com/YunoHost/yunohost/blob/stretch-stable/src/yunohost/tools.py#L361) that got removed recently ... It was previously removed after you create a first user. So if you did *not* create a user doing this, that would explain.

@ImaCrea : do you remember if you created or not a user when triggering this bug ? (your steps to reproduce don't seem to mention it)

If you didn't then we can close the issue since it should now be solved

**Closed as completed** 2020-08-26 17:03 UTC
Labels: :door: SSO
