### ISSUE TITLE
PC 64bit image can't boot on old macbook

### ISSUE THREAD

**Issue by ImaCrea** [YunoHost/issues#1340] opened 2019-04-24 12:07 UTC
Hi there,
I burnt the Yunohost 64bit image on a usb key but for some reason the computer couldn't boot on device.

Hardware: (old) macbook 3,1 (https://igotoffer.com/apple/macbook-31-late-2007)
Steps: 
- power up computer
- pushing Alt key
- no usb bootable device showing

Now I'm following manual install. Debian-amd64-netinst image show on boot screen and install is in progress.

These two images have been burnt on the same usb key, with etcher on the same system and were inserted in the same usb port when trying to boot.

**Comment by narFnarF** [comment] 2023-12-26 16:26
I have the same issue on an old Mac Pro 2009. The USB stick doesn't show up in the boot menu.

Device:
Old Mac Pro 2009 ([model MacPro4,1](https://everymac.com/systems/apple/mac_pro/specs/mac-pro-quad-core-2.66-early-2009-nehalem-specs.html))

Steps to reproduce:
1. Burn the amd64 image using Balena Etcher
2. Reboot holding the Alt key until the boot menu appears
3. Notice that the Yunohost usb key doesn't show up in the menu

Could be related to these issues:
- https://github.com/YunoHost/issues/issues/2080
- https://github.com/YunoHost/issues/issues/2046

**Comment by alexAubin** [comment] 2024-01-27 18:56
Closing as duplicate of https://github.com/YunoHost/issues/issues/2080

**Closed as not planned by alexAubin** 2024-01-27 18:56 UTC
