### ISSUE TITLE
Allow SMTP usage for apps

### ISSUE THREAD

**Issue by Jibec** [YunoHost/issues#1138] opened 2018-06-04 22:45 UTC
We often have apps that supports SMTP but we are still using workarounds because packages can't allow the technical users we create for our apps to use the SMTP.

The problem is when we don't use SMTP, we don't have the DKIM and other benefits, which may lead to blocked emails.

Not a big issue when we are working on apps for our usage, but when we are hosting semi-public application like Weblate, Mastodon, Funkwhale, etc. we need to make sure our emails have the best chance not to be flagged as spam.

Can you please do something about it?

**Comment by alexAubin** [comment] 2018-06-04 22:46
That's a duplicate of https://github.com/YunoHost/issues/issues/947 so closing, sorry :s

**Closed as completed by alexAubin** 2018-06-04 22:46 UTC

**Comment by Jibec** [comment] 2018-06-04 22:52
no worries, thanks, can you please improve the #947 title so it includes "Allow SMTP for apps" or any equivalent?
