### ISSUE TITLE
Provide a way to configure SMTP relays easily

### ISSUE THREAD

**Issue by khimaros** [YunoHost/issues#1649] opened 2020-08-06 04:19 UTC
a common limitation of cloud providers is restricted outbound smtp (port 25) connectivity

one way around this is the use of an smtp relay. this could be a self-hosted relay or a subscription service such as sendgrid, mailgun, or mailjet.

whichever path is chosen, the configuration in postfix is nearly identical quite simple. i have verified this configuration on my own Google Cloud f1-micro instance.

`libsasl2-modules` package is already installed by yunohost so no change required there.

new template variables are needed and should be configurable:

- `{{ smtp_relayhost }}`
- `{{ smtp_relay_user }}`
- `{{ smtp_relay_password }}`

the expected form of `{{ smtp_relayhost }}` is `[smtp.sendgrid.net]:587` (anything allowed for postfix `relayhost`)

the most significant changes would be to `/etc/postfix/main.cf`:

```
smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = hash:/etc/postfix/sasl/relayhost_passwd
smtp_sasl_security_options = noanonymous
smtp_sasl_tls_security_options = noanonymous
smtp_tls_security_level = encrypt
relayhost = {{ smtp_relayhost }}
```

a sasl password map `/etc/postfix/sasl/relayhost_passwd`:

```
{{ smtp_relayhost }} {{ smtp_relay_user }}:{{ smtp_relay_password }}
```

the hash map must be generated with `postmap /etc/postfix/sasl/relayhost_passwd` after the above file is created.

**Comment by alexAubin** [comment] 2020-08-26 17:01
(Duplicate of https://github.com/YunoHost/issues/issues/1348 )

**Comment by alexAubin** [comment] 2020-09-10 22:32
Fixed by https://github.com/YunoHost/yunohost/pull/773

**Closed as completed by alexAubin** 2020-09-10 22:32 UTC
Labels: :mailbox: Email
