### ISSUE TITLE
check somehow that the correct nginx modules are in /etc/nginx/modules-enabled

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1277] opened 2019-01-23 10:55 UTC
This is really an edge case but I end up on an instance where this folder was totally empty for some reason.

I wonder if we shouldn't had them to the regen-conf or the diagnostic file to at least detect this issue?

**Comment by alexAubin** [comment] 2024-01-27 18:47
Closing because I don't know how to reproduce this and this feels out of scope of what we can really diagnose...

**Closed as not planned by alexAubin** 2024-01-27 18:47 UTC
Labels: :stethoscope: Diagnosis
