### ISSUE TITLE
Prevent users from editing profile

### ISSUE THREAD

**Issue by GitBaer** [YunoHost/issues#2095] opened 2022-12-01 05:33 UTC
Hello,

it would be good to get an option to prevent users from editing their profiles (or restrict this by default). I think users should not be able to change or add email addresses, too (only set forward address).

Thank you.

**Comment by eauchat** [comment] 2022-12-01 19:04
I think this is related to #1295, nope?

**Comment by eauchat** [comment] 2022-12-01 19:07
And also to #1675 maybe.

**Comment by alexAubin** [comment] 2022-12-22 14:27
Yes closing as duplicate of existing issues

**Closed as completed by alexAubin** 2022-12-22 14:27 UTC
