### ISSUE TITLE
Be able to include/exclude specific folders from the backup

### ISSUE THREAD

**Issue by Clemorange22** [YunoHost/issues#2008] opened 2022-05-04 12:47 UTC
Hello !

I think it would be great to be able to include or exclude specific folders from the yunohost backup.

I use my yunohost server (raspberry pi 4) as a backup for my family's computers, via Windows save (sorry ;) ).
As my sdcard is only 32Go, I have a HDD drive mounted on /home. So as to save computer's backup on this drive, I needed to create a non-yunohost user named pcbackup on my server, so that all computer backups are saved in /home/pcbackup via a smb share.
The problem is that now, I want to make automatic backups of my yunohost instance on a remote server. And I don't have enought space on that server / bandwidth to backup computer's backups (yes, a lot of backups, I know :) )

And so, selecting precise folders would allow me to backup my user's emails and folders without /home/pcbackup (about 45Go instead of 2To)

Screenshot of yunohost save : 
![image](https://user-images.githubusercontent.com/62897760/166683697-f3b574aa-c605-4d83-b3f8-ccbd4f8ad4de.png)

Borg save : 
![image](https://user-images.githubusercontent.com/62897760/166683839-6bf32028-abad-43dc-8a79-03d8e861fe68.png)

Sorry for my english, I tried to do my best

**Comment by alexAubin** [comment] 2022-05-05 11:02
>And so, selecting precise folders would allow me to backup my user's emails and folders without /home/pcbackup (about 45Go instead of 2To)

Note that **for this specific case** there's a hidden feature which is that you can create file named `.nobackup` in your `/home/pcbackup/` and that will exclude that home folder from the backups

(corresponding piece of code : https://github.com/YunoHost/yunohost/blob/dev/hooks/backup/17-data_home#L15 )

**Comment by alexAubin** [comment] 2022-11-20 19:25
Closing because cf previous trick, and the issue is kinda duplicate from https://github.com/YunoHost/issues/issues/837 and https://github.com/YunoHost/issues/issues/842

**Closed as completed by alexAubin** 2022-11-20 19:25 UTC
