### ISSUE TITLE
diagnostic tool reporting resolv.conf not being a symlink

### ISSUE THREAD

**Issue by msiter-molo** [YunoHost/issues#2298] opened 2023-12-15 07:44 UTC
### Describe the bug

When diagnostic tool identify an issue with resolv.conf not being a symlink, it says : 

_DNS resolution seems to be working, but it looks like you're using a custom /etc/resolv.conf._
    _The file /etc/resolv.conf should be a symlink to **`/etc/resolvconf/run/resolv.conf`** itself pointing to 127.0.0.1 (dnsmasq). If you want to manually configure DNS resolvers, please edit /etc/resolv.dnsmasq.conf._

### Context

Out of the box VPS with Yunohost pre-installed (no matter which one I guess as this warning message can happen in many sitautions)

### To reproduce

just trigger the error messing with resolv.conf

### Expected behavior

If i'm not mistaken, the path in the error message should be 
`/run/resolvconf/resolv.conf`  instead of   `/etc/resolvconf/run/resolv.conf`

**Comment by alexAubin** [comment] 2024-01-27 20:46
Closing because this is the expected behavior I suppose, cf https://github.com/YunoHost/issues/issues/1739

**Closed as not planned by alexAubin** 2024-01-27 20:46 UTC
