### ISSUE TITLE
Dovecot setup uses nonexistent user id 500 leading to non-working IMAP/incoming mail

### ISSUE THREAD

**Issue by hjri** [YunoHost/issues#1985] opened 2022-02-27 14:19 UTC
### Describe the bug

After installing beta version of yunohost on debian 11 ownership of /var/mail was changed to 500:vmail, there is no user with id 500 on my machine. (Install wasn't entirely clean, had some stuff there before including attempt at installing modoboa) and dovecot complains about being unable to run/setuid, incoming mail did not work at all until i manually chownd /var/mail to vmail:vmail and changed user id in dovecot.confg (but now yunohost complains about manually changed file)

### Context

- Hardware: *Hetzner VPS*
- YunoHost version: 11.0.4
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...* (all of the above)
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: as i explained earlier, i manually chown'd and edited stuff to make it work, not tweaking was done beforehand
- Using, or trying to install package version/branch:
- If upgrading, current YunoHost version: 

### To reproduce

perform install of beta version of yunohost

### Expected behavior

Mail works fine, /var/mail belongs to real unix user

**Comment by alexAubin** [comment] 2022-11-20 18:47
Closing because not able to reproduce the issue ...

**Closed as completed by alexAubin** 2022-11-20 18:47 UTC
