### ISSUE TITLE
Switch "public" setting after install

### ISSUE THREAD

**Issue by ahstro** [YunoHost/issues#1378] opened 2019-07-13 10:04 UTC
It would be neat if it was possible to change the "public" setting on an app after install. E.g. I installed calibre-web as private, added a bunch of ebooks, and realized that it'd be cool if my friends could access them without creating a user account.

If I can already do this, sorry for creating the issue and please help me :innocent:

**Comment by maniackcrudelis** [comment] 2019-07-13 10:33
With some app you can change from public to private or the other way.
But that's not yet an official feature, we're working on it.

Calibreweb does not provide such feature yet.
The best thing to do for now is to open an issue on [calibreweb repository](https://github.com/YunoHost-Apps/calibreweb_ynh), to explain what you want to do and ask how to move from private to public manually.

**Comment by ahstro** [comment] 2019-07-16 22:21
Thank you :blush:

**Comment by alexAubin** [comment] 2019-08-07 11:44
Closing because that's a duplicate of https://github.com/YunoHost/issues/issues/306 :s

**Closed as completed by alexAubin** 2019-08-07 11:44 UTC
