### ISSUE TITLE
Buttons doesn't  work as expected

### ISSUE THREAD

**Issue by kay0u** [YunoHost/issues#1287] opened 2019-02-01 22:51 UTC
In the admin panel->Applications->an app, if you click on "uninstall", then click outside the modal (not in cancel or ok but on the grey part), then click on "Define by default",  click on "OK" button on the new modal... The app will uninstall.

**Comment by alexAubin** [comment] 2019-09-22 16:47
Closing the issue because that's really a duplicate of https://github.com/YunoHost/issues/issues/789

**Closed as completed by alexAubin** 2019-09-22 16:47 UTC
Labels: :maple_leaf: Web administration
