### ISSUE TITLE
Add 2fa, such as TOTP, yubikey, backup code, or PGP

### ISSUE THREAD

**Issue by HaywoodFOSS** [YunoHost/issues#1987] opened 2022-03-03 10:53 UTC
Hi
May I suggest to add 2fa support in case of password leaks? TOTP yubikey, backup code, or PGP can be ideal.

**Comment by tituspijean** [comment] 2022-03-03 14:13
Duplicate of https://github.com/YunoHost/issues/issues/238

**Closed as completed by tituspijean** 2022-03-03 14:13 UTC
