### ISSUE TITLE
Yunohost flags unmodified config-v1.1.xml as manually edited on disabling outgoing email

### ISSUE THREAD

**Issue by ashledombos** [YunoHost/issues#2300] opened 2023-12-26 20:38 UTC
### Context

- Hardware: KVM image
- YunoHost version: 11.2.8.2 (stable)
- I have access to my server: Through SSH | through the webadmin 

When creating a domain in Yunohost with the outgoing email option enabled, and later disabling the outgoing email, the file `/var/www/.well-known/mondomaine.org/autoconfig/mail/config-v1.1.xml` is mistakenly flagged as manually modified by Yunohost. This issue occurs both through the web interface and via the command line. The issue arises when disabling the `mail_out` feature but not with the `mail_in` feature, as demonstrated by the following commands:

```sh
~$ sudo yunohost domain config set monomaine.org feature.mail.mail_in -v 0
Info: Saving the new configuration...
Success! Config updated as expected
~$ sudo yunohost domain config set monomaine.org feature.mail.mail_out -v 0
Info: Saving the new configuration...
Warning: The configuration file '/var/www/.well-known/mondomaine.org/autoconfig/mail/config-v1.1.xml' has been manually modified and will not be updated
Success! Configuration updated for 'postfix'
Success! Configuration updated for 'dovecot'
Success! Config updated as expected
```

The file `config-v1.1.xml` appears to be incorrectly marked as manually modified, which is not the case.

### To reproduce

1. Create a domain with the outgoing email feature enabled.
2. Disable the outgoing email feature for the domain.
3. Observe the warning regarding the file `/var/www/.well-known/mondomaine.org/autoconfig/mail/config-v1.1.xml` being flagged as manually modified.

### Expected behavior

The file `config-v1.1.xml` should not be flagged as manually modified when the `mail_out` feature is disabled, as this is a standard operation through the Yunohost interface or command line.

**Comment by alexAubin** [comment] 2024-01-27 20:20
Duplicate of https://github.com/YunoHost/issues/issues/2143

**Closed as not planned by alexAubin** 2024-01-27 20:20 UTC
Labels: :wrench: Configuration
