### ISSUE TITLE
Allow HTTP for onion address or add a function to automatic generate onion address

### ISSUE THREAD

**Issue by Che15ea** [YunoHost/issues#2069] opened 2022-09-17 11:00 UTC
Hello
I would like to use onion address only on my Yunohost services. The general function is fine but there are some problem. For example I would not be able to generate a letsencrypt cert(they don't provide such service), then I have to deal with the warning of self signed cert every time on every address of each session. Gajim cannot perform properly on self signed address as well. Onion address does not need HTTPS certificate, could you please add a function that disable HTTPS for onion address?
It would also be nice if you can add a button that enables tor and generates onion address. It doesn't hurt to setup an onion mirror for each application.
Thank you!

**Comment by alexAubin** [comment] 2022-11-20 21:04
Duplicate of https://github.com/YunoHost/issues/issues/1588

**Closed as completed by alexAubin** 2022-11-20 21:04 UTC
