### ISSUE TITLE
Cannot connect to IMAP dovecot

### ISSUE THREAD

**Issue by yajo** [YunoHost/issues#1659] opened 2020-09-03 06:02 UTC
Since some days ago, I get a lot of these logs in dovecot:

```
sep 03 06:59:50 dovecot[26745]: imap-login: Error: Failed to initialize SSL server context: Couldn't parse DH parameters: error:0909006C:PEM routines:get_name:no start line: Expecting: DH PARAMETERS: user=<>, rip=192.168.0.1, lip=192.168.0.2, session=<jxHadWKu1NvAqAAB>
```

My IMAP client cannot connect, although it was connecting until recently.

I use YunoHost 4.0.5 (testing). I changed nothing recently (just update some packages and apps through UI).

I have renewed the LE cert manually, just in case. Dovecot got restarted. Same problem.

How can I fix that?

**Comment by ericgaspar** [comment] 2020-09-03 06:30
Try to upgrade to YunoHost 4.0.6.1 (stable) and see if the issue is still there

**Comment by yajo** [comment] 2020-09-05 10:31
Is there a way to move an installation from testing to stable?

**Comment by alexAubin** [comment] 2020-09-05 11:03
Just remove "testing" in the file /etc/apt/sources.list.d/yunohost.list

**Comment by alexAubin** [comment] 2020-09-29 14:29
Bumpity bump, did that solve the issue ?

**Comment by yajo** [comment] 2020-09-30 14:32
Sorry, it's in my todo list still... 😅

**Comment by yajo** [comment] 2020-10-03 11:30
I managed to update to stable, yunohost 4.0.8. Updated all. Restarted. It seems that log disappeared from dovecot, but still I cannot connect...

I use Geary. After configuring the account there, it says:

```
Account identifier: account_01
Account provider: GEARY_SERVICE_PROVIDER_OTHER
Service type: GEARY_PROTOCOL_IMAP
Service host: box.recallstack.icu
Error type: SecretError 5
Message: file header mismatch

Back trace:
 * geary_problem_report_construct
 * geary_account_problem_report_construct
 * geary_service_problem_report_construct
 * application_main_window_update_account_status
 * application_controller_get_certificate_manager
 * g_closure_invoke
 * signal_emit_unlocked_R.isra.0
 * g_signal_emit_valist
 * g_signal_emit
 * g_object_dispatch_properties_changed
 * g_object_notify_by_pspec
 * g_closure_invoke
 * signal_emit_unlocked_R.isra.0
 * g_signal_emit_valist
 * g_signal_emit
 * g_object_dispatch_properties_changed
 * g_object_notify_by_pspec
 * geary_client_service_notify_connection_failed
 * geary_imap_client_service_release_session_async
 * g_task_return_now
 * g_task_return.part.0
 * geary_account_notify_service_problem
 * g_task_return_now
 * g_task_return.part.0
 * secret_mediator_clear_token
 * g_task_return_now
 * g_task_return.part.0
 * on_lookup_backend
 * g_task_return_now
 * g_task_return.part.0
 * on_collection_new_async
 * g_task_return_now
 * g_task_return.part.0
 * g_task_return_new_error
 * on_load_contents
 * g_task_return_now
 * g_task_return.part.0
 * load_contents_close_callback
 * async_ready_close_callback_wrapper
 * g_task_return_now
 * complete_in_idle_cb
 * g_main_context_dispatch
 * g_main_context_iterate.constprop.0
 * g_main_context_iteration
 * g_application_run
 * _vala_main
 * __libc_start_main
 * _start
```

Any ideas? :sob:

**Comment by flavioarcega** [comment] 2023-08-07 19:52
I had a problem that the logs was saying: "master: Fatal: service(pop3) access(/usr/lib/dovecot/pop3) failed: No such file or directory"

Then I installed the dovecot-pop3d package and dovecot is up again.

**Comment by alexAubin** [comment] 2024-01-27 20:37
Closing because this is 3ish years old and sounds super-specific to the client used idk

**Closed as not planned by alexAubin** 2024-01-27 20:37 UTC
Labels: :mailbox: Email
