### ISSUE TITLE
[breaking] ssowat lua string arg only after update 4.1

### ISSUE THREAD

**Issue by nin0-0** [YunoHost/issues#1689] opened 2020-12-07 16:28 UTC
since update to 4.1, this breaks mattermost, matrix, and mastodon, and perhaps other services.
 in `/var/log/nginx/` subfolders relevant to the service.

```bash
2020/12/07 11:22:45 [error] 9101#9101: *6516 lua entry thread aborted: runtime error: /usr/share/ssowat/helpers.lua:274: string argument only
stack traceback:
coroutine 0:
       [C]: in function 'decode_base64'
        /usr/share/ssowat/helpers.lua:274: in function 'refresh_logged_in'
        /usr/share/ssowat/access.lua:32: in function </usr/share/ssowat/access.lua:1>, client: <redact>,*server: <redact>, request: "GET /api/v1/timelines/home?since_id=105311953335036503 HTTP/2.0", host: <redact>, referrer: "<subdomain>"
2020/12/07 11:22:45 [error] 9101#9101: *6516 lua entry thread aborted: runtime error: /usr/share/ssowat/helpers.lua:274: string argument only
```

**Comment by kay0u** [comment] 2020-12-10 18:02
Hello, I can't reproduce this error, can you confirm that you still have it after logout/login to the sso, and try to clear your cache (or use another browser)?

**Comment by Thovi98** [comment] 2020-12-10 18:53
I have same problem, with different browsers, since 4.1, with Bitwarden. But I’ve reinstalled it, and the problem appaers (I don’t know if it was the same problem before the reinstallation). 
```
2020/12/10 19:41:16 [error] 8952#8952: *1998 lua entry thread aborted: runtime error: /usr/share/ssowat/helpers.lua:274: string argument only
stack traceback:
coroutine 0:
	[C]: in function 'decode_base64'
	/usr/share/ssowat/helpers.lua:274: in function 'refresh_logged_in'
	/usr/share/ssowat/access.lua:32: in function </usr/share/ssowat/access.lua:1>, client: 51.91.31.157, server: bitwarden.domain.tld, request: "POST /api/ciphers/import HTTP/2.0", host: "bitwarden.domain.tld", referrer: "https://bitwarden.domain.tld/"
```
--> I can’t save passwords anymore since update to 4.1, I don’t know if there is a link with this.


And with Collabora (reinstalled too), it’s not exactly the same error, but concerns ssowat lua too so it’s maybe related : 
```
2020/12/10 19:40:03 [error] 8952#8952: *1923 lua entry thread aborted: runtime error: /usr/share/ssowat/helpers.lua:347: bad argument #1 to 'find' (string expected, got nil)
stack traceback:
coroutine 0:
	[C]: in function 'find'
	/usr/share/ssowat/helpers.lua:347: in function 'authenticate'
	/usr/share/ssowat/helpers.lua:275: in function 'refresh_logged_in'
	/usr/share/ssowat/access.lua:32: in function </usr/share/ssowat/access.lua:1>, client: 89.39.107.146, server: office.domain.tld, request: "GET /loleaflet/dist/admin/admin.html HTTP/2.0", host: "office.domain.tld"
```

--> I have an `500 Internal Server Error` on the settings page domain.tld/loleaflet/dist/admin/admin.html, don’t know if there is a link with this error.

**Comment by kay0u** [comment] 2020-12-14 10:24
Should be fixed by https://github.com/YunoHost/SSOwat/pull/175

**Comment by kay0u** [comment] 2020-12-22 12:27
New testing 4.1.1 with this fix, I'm closing the issue, feel free to reopen it

**Closed as completed by kay0u** 2020-12-22 12:27 UTC
