### ISSUE TITLE
Add SSH pubkey to authorized_keys for admin user from the web admin

### ISSUE THREAD

**Issue by roukydesbois** [YunoHost/issues#1411] opened 2019-08-13 09:44 UTC
As an administrator, 
I'd like to be able to add authorized ssh pubkeys for the admin user in the web admin 
in order to be able to ssh again if I change ssh keys.

My use case is that I had to reset many of my material, and the associated ssh key pairs, and I couldn't easily add them back to the authorized keys

**Comment by Psycojoker** [comment] 2019-08-19 01:23
There is a beginning of work about that there https://github.com/YunoHost/yunohost/pull/345, it just need to be splitted and reworked to be merged into the core.

**Comment by alexAubin** [comment] 2024-07-22 15:29
Duplicate of https://github.com/YunoHost/issues/issues/175

**Closed as not planned by alexAubin** 2024-07-22 15:29 UTC
