### ISSUE TITLE
Post install doesn't work with existing domain other than dydns

### ISSUE THREAD

**Issue by ozzmos** [YunoHost/issues#1332] opened 2019-04-11 15:52 UTC
Choosing existing domain like: mydomain.me
then it throws error
```
Error: Invalid url https://dyndns.yunohost.org/domains (does this site exists?)
Warning: dyndns_provider_unreachable
Info: Installing YunoHost…
Info: The operation 'Postinstall your YunoHost server' has failed!
```

**Comment by Psycojoker** [comment] 2019-05-26 20:49
Really weird o_O

It was probably during our infrastructure outrage so I don't think this is still a problem right now? People would have scream a lot since more than one month.

**Comment by alexAubin** [comment] 2019-09-22 16:57
I really doubt this is related to the dyndns domain here ... The message `Installing YunoHost…` suggests that it effectively start the install and went beyond the dyndns stuff step.

Can you provide more detail on what happened ? Did you end up solving it ?

**Comment by yan5b** [comment] 2019-09-25 16:38
Hello I'm also having the same issue same error about the dydns the post install work but it impact riot any solutions ?

**Comment by alexAubin** [comment] 2019-09-25 16:41
Uh wokay, can you elaborate ... What did you want to achieve, what did you do, what works and what doesn't, what message do you get, what do you expected to get instead ...

**Comment by yan5b** [comment] 2019-09-25 16:54
Wow thanks for your fast reply. Basicly I've pass the last 5 days trying to resolve that. 
Let me explain: 

I have install debian on my vps and use the command line to curl yunohost.
After that I've use the post install command and get 2 errors 

`Error: Invalid url https://dyndns.yunohost.org/domains (does this site exists?)
Warning: dyndns_provider_unreachable
Info: Installing YunoHost…
Info: The configuration file '/etc/nsswitch.conf' is now managed by YunoHost (category nsswitch).
Success! The configuration has been updated for category 'nsswitch'
Info: The configuration file '/etc/nslcd.conf' is now managed by YunoHost (category nslcd).
Success! The configuration has been updated for category 'nslcd'
Success! LDAP has been initialized
Success! The configuration has been updated for category 'ssl'
Success! The local certification authority has been created.
Success! Successfully installed a self-signed certificate for domain bbi-websec.com!
Success! The domain has been created
Success! The SSOwat configuration has been generated
Success! The main domain has been changed
Info: Your root password have been replaced by your admin password.
Success! The administration password has been changed
Success! The firewall has been reloaded
Error: Unable to retrieve the remote application list yunohost: HTTPSConnectionPool(host='app.yunohost.org', port=443): Max retries exceeded with url: /apps.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbed8913d10>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Synchronizing state of yunohost-firewall.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable yunohost-firewall
Success! The service 'yunohost-firewall' has been enabled
Success! The service 'yunohost-firewall' has been started
Info: The configuration file '/etc/default/glances' is now managed by YunoHost (category glances).
Success! The configuration has been updated for category 'glances'
Info: The configuration file '/etc/metronome/metronome.cfg.lua' is now managed by YunoHost (category metronome).
Success! The configuration has been updated for category 'metronome'
Success! The configuration has been updated for category 'nginx'
Info: The configuration file '/etc/postfix/master.cf' is now managed by YunoHost (category postfix).
Info: The configuration file '/etc/postfix/main.cf' is now managed by YunoHost (category postfix).
Info: The configuration file '/etc/default/postsrsd' is now managed by YunoHost (category postfix).
Success! The configuration has been updated for category 'postfix'
Info: The configuration file '/etc/etckeeper/etckeeper.conf' is now managed by YunoHost (category yunohost).
Success! The configuration has been updated for category 'yunohost'
Success! The configuration has been updated for category 'rspamd'
Info: The configuration file '/etc/default/dnsmasq' is now managed by YunoHost (category dnsmasq).
Info: The configuration file '/etc/dnsmasq.conf' is now managed by YunoHost (category dnsmasq).
Success! The configuration has been updated for category 'dnsmasq'
Info: The configuration file '/etc/fail2ban/jail.conf' is now managed by YunoHost (category fail2ban).
Success! The configuration has been updated for category 'fail2ban'
Info: The configuration file '/etc/mysql/my.cnf' is now managed by YunoHost (category mysql).
Success! The configuration has been updated for category 'mysql'
Info: The configuration file '/etc/avahi/avahi-daemon.conf' is now managed by YunoHost (category avahi-daemon).
Success! The configuration has been updated for category 'avahi-daemon'
Info: The configuration file '/etc/dovecot/dovecot.conf' is now managed by YunoHost (category dovecot).
Success! The configuration has been updated for category 'dovecot'
Success! The configuration has been updated for category 'slapd'
Info: The configuration file '/etc/ssh/sshd_config' is now managed by YunoHost (category ssh).
Success! The configuration has been updated for category 'ssh'
Success! YunoHost has been configured
Warning: The post-install is finished but YunoHost needs at least one user to work correctly, you should add one using 'yunohost user create $username' or the admin interface.`

If I pass the install I can normally use yunohost except for one things - Riot and synapse
Riot, after installation it says that my internet connection is not stable.
When I'm checking synapse on the service section - it says activation in red ...

**Comment by alexAubin** [comment] 2019-09-25 17:03
Hmmmokay, well it does look like there was some weird stuff happening with domain name resolution ... I'm curious to know what exactly Riot and Synapse mean by "connection is not stable" x_X

Are you able now to resolve domain names ? For example you can try to run `ping -c 3 wikipedia.org` on your server and see if it does ping the IP (which implicitly means that it was able to resolve the domain name)

**Comment by yan5b** [comment] 2019-09-25 17:05
`PING wikipedia.org (91.198.174.192) 56(84) bytes of data.
64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=1 ttl=58 time=26.4 ms
64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=2 ttl=58 time=25.6 ms

--- wikipedia.org ping statistics ---
3 packets transmitted, 2 received, 33% packet loss, time 2003ms
rtt min/avg/max/mdev = 25.614/26.027/26.440/0.413 ms
`

**Comment by alexAubin** [comment] 2019-09-25 17:16
>3 packets transmitted, 2 received, 33% packet loss, time 2003ms

Hmmm this packet loss is weird ? Can you run `ping -c 30 wikipedia.org` (so 30 pings) to see if that was just a random fluke or if there's significant packet loss ?

>Couldn't listen on ::1:8008: [Errno 99] Cannot assign requested address.

Hmmm, does `lsof -i | grep 8008` shows a process already listenin on port 8008 ?

**Comment by yan5b** [comment] 2019-09-25 17:20
Ping looks good  and the grep passed without error 
> ping -c 30 wikipedia.org
> PING wikipedia.org (91.198.174.192) 56(84) bytes of data.
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=1 ttl=58 time=20.9 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=2 ttl=58 time=20.7 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=3 ttl=58 time=20.7 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=4 ttl=58 time=21.6 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=5 ttl=58 time=23.9 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=6 ttl=58 time=20.6 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=7 ttl=58 time=21.0 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=8 ttl=58 time=21.5 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=9 ttl=58 time=21.1 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=10 ttl=58 time=20.7 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=11 ttl=58 time=20.6 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=12 ttl=58 time=20.7 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=13 ttl=58 time=21.0 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=14 ttl=58 time=20.9 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=15 ttl=58 time=20.9 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=16 ttl=58 time=20.9 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=17 ttl=58 time=22.3 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=18 ttl=58 time=20.9 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=19 ttl=58 time=21.6 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=20 ttl=58 time=20.7 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=21 ttl=58 time=20.7 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=22 ttl=58 time=21.7 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=23 ttl=58 time=20.6 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=24 ttl=58 time=22.0 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=25 ttl=58 time=20.8 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=26 ttl=58 time=20.6 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=27 ttl=58 time=22.4 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=28 ttl=58 time=20.6 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=29 ttl=58 time=20.9 ms
> 64 bytes from text-lb.esams.wikimedia.org (91.198.174.192): icmp_seq=30 ttl=58 time=21.0 ms
> 
> --- wikipedia.org ping statistics ---
> 30 packets transmitted, 30 received, 0% packet loss, time 29045ms
> rtt min/avg/max/mdev = 20.655/21.202/23.932/0.715 ms
>

**Comment by AkselRocks** [comment] 2020-02-26 20:25
Have the same issue as @yan5b 
installation errors like above, yh admin panel works good, installation of searx and peertube with no error, but using 
- searx:  "Internal Server Error"
- peertube: "Invalid client: client is invalid"

could you work-around this issue or even solve it?

**Comment by alexAubin** [comment] 2020-04-28 03:51
Alright folks ... the original issue what about a very specific issue and we have no more ... then discussion drifted to other unrelated things ... Closing because this is going nowhere.

@AkselRocks : you probably found it since then but for peertube you're looking for https://github.com/YunoHost-Apps/peertube_ynh/issues/119

**Closed as completed by alexAubin** 2020-04-28 03:51 UTC
